<?php

use Drupal\agri_admin\Utils;

/**
 * @file
 * WxT Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function grstheme_bootstrap_preprocess_html(&$variables) {
  $route_match = Utils::getRouteName();
  if ($route_match == 'email_template.content') {
    // Removes the json drupal settings that is added to the page.
    // The email sending tool doesn't like this part so we're removing it.
    unset($variables['#attached']); // Not needed for the en/news-bulletin-email page.
  }

  $current_path = \Drupal::service('path.current')->getPath();
  $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['langID'] = $langId;
  $theme = \Drupal\bootstrap\Bootstrap::getTheme();
  $themedir = $theme->getPath();
  $variables['current_path'] = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  // Add class attribute (current role names) to the body class (for styling).
  // Ex: administrator, comms, reviewer, anonymous.
  $roles = \Drupal::currentUser()->getRoles();
  foreach ($roles as $role_name) {
    $variables['attributes']['class'][] = $role_name;
  }

  // Begin logic to grab moderation state and add it to the body class for styling.
  // This section is required for view node identify draft revisions as 'pink'.
  // Corresponding draft pink css is in css/style.scss.

  $variables['current_path'] = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  // Add node id to the body class.
  $node = \Drupal::routeMatch()->getParameter('node');
  $node_revision = \Drupal::routeMatch()->getParameter('node_revision');
  $routeMatchParams = \Drupal::routeMatch()->getParameters();
  $nid = 0;
  $vid = 0;
  $revision_is_object = FALSE;
  $nodeLoaded = 0;
  $archived = '';
  if ($node) {
    // Workaround for https://www.drupal.org/project/drupal/issues/2730631 .
    // Workaround for inconsistent router behaviour, see comments in issue 2730631.
    // TODO, follow up on issue 2730631.
    $published = 'published-yes';
    $is_unpublished = '';
    $is_pending_draft = '';
    $nodeType = '';
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');

    if(is_string($node) && is_numeric($node)) {
      $nid = $node;
    }
    else if (gettype($node) == 'object') {
      $nid = $node->id();
      $nodeType = $node->getType();
      $vid = $node->getRevisionId();
      // Load a single node.
      $nodeLoaded = $node_storage->load($nid);
    }

    $variables['attributes']['class'][] = 'node-' . $nid;

    if ($nid == 49) {
      $variables['attributes']['class'][] = 'news-article-form-page';
    }
    if ($nid == 50) {
      $variables['attributes']['class'][] = 'employment-opportunity-request-form-page';
    }

    if (is_string($node_revision) && is_numeric($node_revision)) {
      $vid = $node_revision;
    }

    if (gettype($node_revision) == 'object') {
      $revision_is_object = TRUE;
      if (!method_exists($node_revision, 'getRevisionId')) {
        return;
      }
      $vid = $node_revision->getRevisionId();
    }

    if ($vid == 0 && gettype($node_revision) == 'object') {
      // Get the revision id.
      $vid = $nodeLoaded->getRevisionId();
    }

    if ($vid) {
      // Load the revision.
      $this_revision = $node_revision;
      if (!$revision_is_object) {
        $this_revision = \Drupal::entityTypeManager()->getStorage('node')->loadRevision($vid);
      }
      if ($this_revision->hasTranslation($langId)) {
        // Get current language revision.
        $this_revision = $this_revision->getTranslation($langId);
      }
      // Get the revisions moderation state.
      $this_revision_state = $this_revision->get('moderation_state')->getString();
      if ($this_revision_state != 'published' && $this_revision_state != 'archived') {
        $published = 'published-no';
        $is_unpublished = 'is-unpublished';
        // Determine if revision is pending-draft (unpublished with previous published revision).
        if (!$this_revision->isDefaultRevision()) {
          // Since this is NOT the default revision, it means that the current revision state is not draft.
          // So given our workflow configuration we can assume that this is a 'pending-draft'.
          $is_pending_draft = 'pending-draft';
        }
      }
      if ($this_revision_state == 'archived') {
        $published = 'published-no-is-archived';
        $archived = 'archived';
      }
      $nodeType = $this_revision->getType();
    }

    if (!empty($nodeType)) {
      $variables['attributes']['class'][] = $nodeType;
    }
    $variables['attributes']['class'][] = 'node-' . $nid;
    // Add node published status to body class.
    $variables['attributes']['class'][] = $published;
    if (!empty($archived)) {
      $variables['attributes']['class'][] = $archived;
    }
    if (!empty($is_unpublished)) {
      $variables['attributes']['class'][] = $is_unpublished;
    }
    if (!empty($is_pending_draft)) {
      $variables['attributes']['class'][] = $is_pending_draft;
    }

  }
  // End of logic to grab moderation state and add it to the body class for styling.
  
  $host = \Drupal::request()->getHost();
  $prod = FALSE;
  if (stripos($host, 'wip') > 0 || stripos($host, 'grisource.agr.gc.ca') > 0) {
    $prod = TRUE;
  }
  // Adobe Analytics JS library.
  if (\Drupal::currentUser()->isAnonymous() && $prod) {
    $variables['#attached']['library'][] = 'grstheme_bootstrap/grstheme-externaladobetmprodjs';
  }
  else {
    $variables['#attached']['library'][] = 'grstheme_bootstrap/grstheme-externaladobetmstagingjs';
  }


}


/**
 * Implments hook_preprocess_node.
 */
function grstheme_bootstrap_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_classification') {
    $block = \Drupal\agri_admin\UtilsBlock::getRendered('employment_classification_groups');
    $variables['empl_classification_block'] = $block;
  }
}


/**
 * Implements hook_form_alter.
 */
function grstheme_bootstrap_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
/*  We decide to use the Drupal HTML 5 validaton and Drupal default preview funcitonality - Preview page is displayed on the same tab.
    committed out the logic for adding custom preview message */
  if ($form_id === 'node_news_form' || $form_id === 'node_news_edit_form') {
    // $text = t("<p class='preview-helptext-paragraph'>Preview your article to see how it will look in <strong>news@work</strong>.  If your article doesn't appear correct, close the preview window and edit it again.</p>");
    $form['actions']['preview']['#prefix'] = '<div class="preview-wrapper">';
    $form['actions']['preview']['#suffix'] =  '</div>';
    // $textsubmitmsg = t("<p>When you've completed and previewed your article, click submit to send it to the news@work coordinator.</p>");
    $form['actions']['submit']['#prefix'] = '';
    $form['actions']['submit']['#prefix'] = "<div class='submit-helptext-paragraph'></div>";
  }

  if ($form_id === 'node_empl_form' || $form_id === 'node_empl_edit_form') {
    //$text = t("<p class='preview-helptext-paragraph'>Preview your employment opportunity in a <strong>new window</strong> before submitting to ensure that all of the information is correct.<br/><strong>Close</strong> the preview window to return to the form.</p>");
    $form['actions']['preview']['#prefix'] = '<div class="preview-wrapper">';
    $form['actions']['preview']['#suffix'] = '</div>';
  }
}


/**
 * Implements hook_preprocess_textarea().
 */
function grstheme_bootstrap_preprocess_textarea(&$variables) {
  if (is_object($variables['attributes'])) {
    $attribute_obj = $variables['attributes'];
    $attr_array = $attribute_obj->toArray();
    if (isset($attr_array['aria-describedby'])) {
      if ($attr_array['aria-describedby'] == 'edit-body-0-summary--description') {
        $attribute_obj->removeAttribute('aria-describedby');
        $variables['attributes'] = $attribute_obj;
        //\Drupal\agri_admin\AgriAdminHelper::addToLog('debug : <pre>' . print_r($attr_array,TRUE) . '</pre>' , TRUE);
      }

      if ($attr_array['aria-describedby'] == 'edit-body-etuf-fr-0-summary--description') {
        $attribute_obj->removeAttribute('aria-describedby');
        $variables['attributes'] = $attribute_obj;
      }
    }
  }
}


/**
 * Implements hook_preprocess_input().
 */
function grstheme_bootstrap_preprocess_input(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (is_object($variables['attributes'])) {
      $attribute_obj = $variables['attributes'];
      $attr_array = $attribute_obj->toArray();
      if (isset($attr_array['id']) ) {
        if ($attr_array['id'] == 'edit-field-date-closing-0-value-date' ) {
          $attribute_obj->removeAttribute('aria-required');
          $variables['attributes'] = $attribute_obj;
        }

        if ($attr_array['id'] == 'edit-field-posted-0-value-date' ) {
          $attribute_obj->removeAttribute('aria-required');
          $variables['attributes'] = $attribute_obj;
        }
      }
    }
  }
}


/**
 * Implements hook_preprocess_field_multiple_value_form().
 */
function grstheme_bootstrap_preprocess_field_multiple_value_form(&$vars) {
  if (!\Drupal::currentUser()->isAnonymous()) { return; }
  // Anonymous only logic below.

  // Remove weight option for multivalue fields.
  if (isset($vars['table']['#tabledrag'])) {
    unset($vars['table']['#tabledrag']);
    array_pop($vars['table']['#header']);
    foreach ($vars['table']['#rows'] as &$row) {
      foreach ($row['data'] as $key => $rowrowdata) {
        if (!$rowrowdata['data']) {
          unset($row['data'][$key]);
        }
      }
    }
  }
}


/**
 * Implements hook_preprocess_fieldset().
 */
function grstheme_bootstrap_preprocess_fieldset(&$variables) {
  unset($variables['attributes']['required']);
  unset($variables['attributes']['aria-required']);
  unset($variables['attributes']['aria-invalid']);
}


/**
 * Implements hook_preprocess_select().
 */
function grstheme_bootstrap_preprocess_select(&$variables) {
  if (!isset($variables['element']['#field_name'])) { return; }
  if (\Drupal::currentUser()->isAnonymous()) {
    if ($variables['element']['#field_name']) {
      if ($variables['element']['#field_name']== 'field_newstype') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_to') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_branch') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_class_id') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_class_sub') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_class_level') {
        $variables['attributes']['size'] = 1;
      }
    }
  }
}


/**
 * Implements hook_preprocess_form_element_label().
 */
function grstheme_bootstrap_preprocess_form_element_label(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (isset($variables['attributes']['for']) && $variables['attributes']['for']) {
      if ($variables['attributes']['for'] == 'edit-advanced' ) {
        // This squelches w3c error for label that has no element.
        // Since we have removed edit-advanced section we also adjust its label.
        unset($variables['element']);
        unset($variables['attributes']['for']);
        unset($variables['attributes']['class']);
        $variables['attributes']['class'] = 'sr-only';
      }
    }
  }
}


/**
 * Implements grstheme_bootstrap_preprocess_page hook.
 */

function grstheme_bootstrap_preprocess_page(&$vars) {
  /* hide view and lastest version TABS in the page content */
  $current_uri = \Drupal::request()->getRequestUri();
  $regex_token = '/\/latest\?auHash=([a-zA-Z]|[0-9]|[_]|[-]){43}/';
  if (preg_match($regex_token, $current_uri)) {
    if (\Drupal::currentUser()->isAnonymous() && $vars['page']['#type'] == 'page' ) {
      $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
      if ($langId == 'en') {
        $patten = '/<nav class="tabs mrgn-tp-md mrgn-bttm-md" aria-label="Tabs">/';
        $replacement = '<nav class="tabs mrgn-tp-md mrgn-bttm-md" style="display: none;" aria-label="Tabs">';
      }
      else {
        $patten = '/<nav class="tabs mrgn-tp-md mrgn-bttm-md" aria-label="Onglets">/';
        $replacement = '<nav class="tabs mrgn-tp-md mrgn-bttm-md" style="display: none;" aria-label="Onglets">';
      }
      $content = $vars['page']['content']['system_main']['#markup'];
      if (isset($content)) {
        $content = preg_replace($patten, $replacement, $content);
        if (isset($content)) {
          $vars['page']['content']['system_main']['#markup'] = \Drupal\Core\Render\Markup::create($content);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_links().
 */
function grstheme_bootstrap_preprocess_links__comment(&$variables) {
  $blog_anon = \Drupal::config('wxt_overrides.settings')->get('blog_anon');
  $current_user = \Drupal::currentUser();
  $authenticated = $current_user->isAuthenticated();
  if ($authenticated && $blog_anon) {
    $links = $variables['links'];
    foreach($links as $key => $link) {
      if ($link['text'] == 'Reply' || $link['text'] == 'Edit' || $link['text'] == 'Delete') {
        unset($links[$key]);
      }
    }
    $variables['links'] = $links;
  }
}

/**
 * Implements hook_preprocess_field__node__field_blog_tags__blog_post().
 */
function grstheme_bootstrap_preprocess_field__node__field_blog_tags__blog_post(&$variables) {
  $blog_hide_tags = \Drupal::config('wxt_overrides.settings')->get('blog_hide_tags');
  if ($blog_hide_tags) {
    $variables['items'] = NULL;
    $variables['label'] = NULL;
  }
}

/**
 * Implements hook_preprocess_links__node().
 */
function grstheme_bootstrap_preprocess_links__node(&$variables) {
  $blog_hide_link = \Drupal::config('wxt_overrides.settings')->get('blog_hide_link');
  $current_user = \Drupal::currentUser();
  $authenticated = $current_user->isAuthenticated();
  if ($authenticated && $blog_hide_link && isset($variables['links']['blog_usernames_blog'])) {
    unset($variables['links']);
    unset($variables['heading']);
  }
  if ($blog_hide_link && isset($variables['links']['blog_usernames_blog'])) {
    unset($variables['links']['blog_usernames_blog']);
  }
  if ($blog_hide_link && isset($variables['links']['comment-add'])) {
    unset($variables['links']['comment-add']);
  }
}

/**
 * Implements hook_preprocess_links__node().
 */
function grstheme_bootstrap_preprocess_field__node__field_blog_comments__blog_post(&$variables) {
  $variables['blog_hide_link'] = FALSE;
  $variables['blog_suggest_logout'] = FALSE;
  $blog_hide_link = \Drupal::config('wxt_overrides.settings')->get('blog_hide_link');
  $current_user = \Drupal::currentUser();
  $authenticated = $current_user->isAuthenticated();
  if ($authenticated && $blog_hide_link) {
    $variables['blog_hide_link'] = TRUE;
    $variables['blog_suggest_logout'] = TRUE;
  }
}

