<?php

/**
 * @file
 * WxT Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function grstheme_bootstrap_preprocess_html(&$variables) {

  $current_path = \Drupal::service('path.current')->getPath();
  $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['langID'] = $langId;
  $theme = \Drupal\bootstrap\Bootstrap::getTheme();
  $themedir = $theme->getPath();
  $variables['current_path'] = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  // Add node id to the body class.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    // Workaround for https://www.drupal.org/project/drupal/issues/2730631 .
    // Workaround for inconsistent router behaviour, see comments in issue 2730631.
    $nodeType = '';
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');

    if (is_string($node) && is_numeric($node)) {
      $nid = $node;
    }
    else if (gettype($node) == 'object') {
      $nid = $node->id();
      $nodeType = $node->getType();
      $vid = $node->getRevisionId();
    }
    if ($nid == 49) {
      $variables['attributes']['class'][] = 'news-article-form-page';
    }
    if ($nid == 50) {
      $variables['attributes']['class'][] = 'employment-opportunity-request-form-page';
    }
    $variables['attributes']['class'][] = 'node-' . $nid;
  }

}


/**
 * Implments hook_preprocess_node.
 */
function grstheme_bootstrap_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_classification') {
    $block = \Drupal\agri_admin\UtilsBlock::getRendered('employment_classification_groups');
    $variables['empl_classification_block'] = $block;
  }
}

/**
 * Implements hook_form_alter.
 */
function grstheme_bootstrap_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id === 'node_news_form' || $form_id === 'node_news_edit_form') {
      $text = t("<p class='preview-helptext-paragraph'>Preview your article to see how it will look in <strong>news@work</strong>.  If your article doesn't appear correct, close the preview window and edit it again.</p>");
      $form['actions']['preview']['#prefix'] = '<br><div class="preview-wrapper">';
      $form['actions']['preview']['#suffix'] = $text . '</div>';
  }

  if ($form_id === 'node_empl_form' || $form_id === 'node_empl_edit_form') {
      $text = t("<p class='preview-helptext-paragraph'>Preview your employment opportunity in a <strong>new window</strong> before submitting to ensure that all of the information is correct.<br/><strong>Close</strong> the preview window to return to the form.</p>");
      $form['actions']['preview']['#prefix'] = '<br><div class="preview-wrapper">';
      $form['actions']['preview']['#suffix'] = $text . '</div>';
  }
}
