id: wxt_ism_policy_strong
label: 'Web Experience Toolkit ISM Policy (Strong)'
password_reset: 90
langcode: en
policy_constraints:
  0:
    id: password_length
    character_length: 10
    character_operation: minimum
  3:
    id: character_types
    character_types: 3
  4:
    id: character_types
    character_types: 3
  5:
    id: password_policy_character_constraint
    character_count: 1
    character_type: special
  6:
    id: password_length
    character_length: 8
    character_operation: minimum
roles:
  authenticated: authenticated
  administrator: administrator
  creator: creator
  editor: editor
  reviewer: reviewer
  news_ccpub: news_ccpub
  empl_cspub: empl_cspub
