warmers:
  sitemap:
    id: sitemap
    frequency: '300'
    batchSize: '50'
    sitemaps: {  }
    minPriority: '0'
    headers: {  }
    verify: 1
  cdn:
    id: cdn
    frequency: '300'
    batchSize: '50'
    urls: {  }
    headers: {  }
    verify: 1
  entity:
    id: entity
    frequency: 300
    batchSize: 50
    entity_types:
      'node:empl': 'node:empl'
      'node:landing_page': 'node:landing_page'
      'node:news': 'node:news'
      'node:page': 'node:page'
      'node:webform': 'node:webform'
      'page:page': 'page:page'
      'page_variant:page_variant': 'page_variant:page_variant'
      'view:view': 'view:view'
_core:
  default_config_hash: wLhhL58IKPWkAbhxcI6gpCna7d431Q7kM0y-Om92BUQ
