#Ensure that these tests run on our gitlab runner, set the default tags.
default:
  tags:
    - agrisource

stages:
  - test
  - d8

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  
trigger_build:
  stage: d8
  script:
    - "curl -X POST -F token=c565062b2dd906367f3f4746a6e72d -F ref=master -F variables[SOURCE_COMMIT_MSG]=\"$CI_COMMIT_MESSAGE\" -F variables[SOURCE_URL]=\"$CI_PROJECT_URL\" -F variables[SOURCE_SHORT_SHA]=$CI_COMMIT_SHORT_SHA -F variables[SOURCE_SHA]=$CI_COMMIT_SHA https://gitlab.com/api/v4/projects/16646420/trigger/pipeline"
  only:
    - 11.1.x-wxt-6.1.x
