<?php

/**
 * @file
 * Primary module hooks for linkchecks module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */


function linkchecks_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    $current_route = \Drupal::routeMatch()->getRouteName();
    if ($current_route == 'view.broken_links_report.page_1') {
      //$form['#attached']['library'] = 'linkchecks/linkchecks';
      //\Drupal\agri_admin\AgriAdminHelper::addToLog($form_id, TRUE);
      //\Drupal\agri_admin\AgriAdminHelper::addMessage($form_id, TRUE);
      //\Drupal\agri_admin\AgriAdminHelper::addToLog($current_route, TRUE);
      //\Drupal\agri_admin\AgriAdminHelper::addMessage($current_route, TRUE);
    }
  }
}



/**
 * Implements hook_page_attachments().
 *
 * Adds the agri-admin libraries to each page.
 
function linkchecks_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'linkchecks/linkcheckblock';
  $current_route = \Drupal::routeMatch()->getRouteName();
        \Drupal\agri_admin\AgriAdminHelper::addToLog($current_route, TRUE);
      \Drupal\agri_admin\AgriAdminHelper::addMessage($current_route, TRUE);
  if ($current_route == 'content_moderation.admin_moderated_content' || $current_route == 'system.admin_content') {
  }
}*/