name: AgriSource
mail: j@7pro.ca
slogan: ''
page:
  0: ''
  1: ''
  front: /welcome
  403: /system/404
  404: /system/404
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: uNOHaKWnoIbi-Q7d7NTqX2PeF_cwCaM9tTmwBoM2COA
uuid: 3f663ae8-967e-4ef3-a4be-3854d8c56709
