_core:
  default_config_hash: uNOHaKWnoIbi-Q7d7NTqX2PeF_cwCaM9tTmwBoM2COA
langcode: en
uuid: 3f663ae8-967e-4ef3-a4be-3854d8c56709
name: 'AgriSource Dev'
mail: j@9pro.ca
slogan: ''
page:
  403: /system/404
  404: /system/404
  front: /node/20
  0: ''
  1: ''
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
