<?php


use Drupal\agri_admin\AgriAdminHelper;
use Drupal\agri_admin\Utils;
use Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * @file
 * Primary module hooks for WxT Overrides module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */



/**
 * Implements hook_help().
 */
function wxt_overrides_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wxt_overrides':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The WxT Overrides module provides configuration options for the blog node and comments behavior and also provides page attachements for meta information (in the source code there is meta logic for dcterms and aafc subjects for example.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';

      $output .= '<dt>' . t('Configuring Wxt Overrides') . '</dt>';
      $output .= '<dd>' . t('The WxT Overrides module provides page for configuring hide and comment behaviors for the blog <a href=":config">WxT Overrides settings</a>.', [':config' =>  Url::fromRoute('wxt_overrides.settings_form')->toString()]) . '</dd>';

      $output .= '</dl>';
      return $output;

    case 'wxt_overrides.settings_form':
      return '<p>' . t('This page shows you all available administration tasks for Wxt Overrides module.') . '</p>';

  }
}


/**
 * Implements hook_page_attachments().
 *
 * Provide aafc metatag elements in the head to each page.
 */
function wxt_overrides_page_attachments(array &$page) {

  $DEBUG = FALSE;
  if ($DEBUG && $fp = fopen('modules/custom/wxt_overrides/debug.txt', 'a')) {
    fwrite($fp, print_r($page, TRUE) . "\n");
    fclose($fp);
  }

  $metatags_module_head = $page['#attached']['html_head'];
  if (!isset($metatags_module_head)) {
    return;
  }
  $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
  // Add page meta.
  foreach ($metatags_module_head as $key => $value) {
    if (isset($value[0]['#attributes']['name'])) {
      $name = $value[0]['#attributes']['name'];
      if ($name == 'dcterms.language') {
        unset($page['#attached']['html_head'][$key]);
      }
    }
  }

  $dctermsaccessRights = [
    '#tag' => 'meta',
    '#attributes' => [
      'name'  => 'dcterms.accessRights',
      'content'   => '3',
    ],
  ];

  if ($langId == 'en') {
    $dctermslanguage = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.language',
        'title'     => 'ISO639-2',
        'content'   => 'eng',
      ],
    ];

    $dctermsservice = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.service',
        'title'     => '',
        'content'   => 'AAFC_AgriSource',
      ],
    ];
  }

  if ($langId == 'fr') {
    $dctermslanguage = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.language',
        'title'     => 'ISO639-2',
        'content'   => 'fra',
      ],
    ];

    $dctermsservice = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.service',
        'title'     => '',
        'content'   => 'AAC_AgriSource',
      ],
    ];
  }

  $page['#attached']['html_head'][] = [$dctermsaccessRights, 'dcterms.accessRights'];
  $page['#attached']['html_head'][] = [$dctermslanguage, 'dcterms.language'];
  $page['#attached']['html_head'][] = [$dctermsservice, 'dcterms.service'];

  $node = \Drupal::routeMatch()->getRawParameter('node');
  if (!isset($node)) {
    $webform = \Drupal::routeMatch()->getRawParameter('webform');
    if (isset($webform)) {
      // Implment the logic by adding the hard codes for meta data (dcterms.issued and dcterms.modified).
      // The team decided to use the hard code approach in the short term.
      if (($webform == 'publishing_and_creative_services') || ($webform == 'video_production_request_form')) {
        $datestr = '2020-10-31';
        $dctermsissued = [
          '#tag' => 'meta',
          '#attributes' => [
            'name'  => 'dcterms.issued',
            'title'     => 'W3CDTF',
            'content'   => $datestr,
          ],
        ];

        $dctermsmodified = [
          '#tag' => 'meta',
          '#attributes' => [
            'name'  => 'dcterms.modified',
            'title'     => 'W3CDTF',
            'content'   => $datestr,
          ],
        ];
      }
      else {
        // set a default value.
        $datestr = '2020-10-31';
        $dctermsissued = [
          '#tag' => 'meta',
          '#attributes' => [
            'name'  => 'dcterms.issued',
            'title'     => 'W3CDTF',
            'content'   => $datestr,
          ],
        ];

        $dctermsmodified = [
          '#tag' => 'meta',
          '#attributes' => [
            'name'  => 'dcterms.modified',
            'title'     => 'W3CDTF',
            'content'   => $datestr,
          ],
        ];
      }
      $page['#attached']['html_head'][] = [$dctermsissued, 'dcterms.issued'];
      $page['#attached']['html_head'][] = [$dctermsmodified, 'dcterms.modified'];
    }
    else 
    {
      return;
    }
  }

  // Add page meta.
  $summary = '';
  $route_match = Utils::getRouteName();
  if ($route_match == 'entity.node.canonical' && isset($page['#attached']['html_head'])) {
    $metatags_module_head = $page['#attached']['html_head'];
    foreach ($metatags_module_head as $key => $value) {
      if (isset($value[0]['#attributes']['name'])) {
        $name = $value[0]['#attributes']['name'];
        if ($name == 'dcterms.language') {
          unset($page['#attached']['html_head'][$key]);
          $page['#attached']['html_head'][] = [$dctermslanguage, 'dcterms.language'];
        }
        if ($name == 'dcterms.description') {
          $summary = $value[0]['#attributes']['content'];
          unset($page['#attached']['html_head'][$key]);
        }

        if ($name == 'keywords') {
          $content = $value[0]['#attributes']['content'];
          $keywords = [
            '#tag' => 'meta',
            '#attributes' => [
              'name'  => 'keywords',
              'content'   => $content,
            ],
          ];
          unset($page['#attached']['html_head'][$key]);
        }

        if ($name == 'dcterms.creator') {
          $content = $value[0]['#attributes']['content'];
          $dctermscreator = [
            '#tag' => 'meta',
            '#attributes' => [
              'name'  => 'dcterms.creator',
              'content'   => $content,
            ],
          ];
          unset($page['#attached']['html_head'][$key]);
          $page['#attached']['html_head'][] = [$dctermscreator, 'dcterms.creator'];
        }
        if ($name == 'dcterms.title') {
          $content = $value[0]['#attributes']['content'];
          $dctermstitle = [
            '#tag' => 'meta',
            '#attributes' => [
              'name'  => 'dcterms.title',
              'content'   => $content,
            ],
          ];
          unset($page['#attached']['html_head'][$key]);
          $page['#attached']['html_head'][] = [$dctermstitle, 'dcterms.title'];
        }
        if ($name == 'dcterms.type') {
          $content = $value[0]['#attributes']['content'];
          $dctermstype = [
            '#tag' => 'meta',
            '#attributes' => [
              'name'  => 'dcterms.type',
              'title'     => 'gctype',
              'content'   => $content,
            ],
          ];
          unset($page['#attached']['html_head'][$key]);
        }
        if ($name == 'dcterms.subject') {
          $content = $value[0]['#attributes']['content'];
          $aafcsubject = [
            '#tag' => 'meta',
            '#attributes' => [
              'name'  => 'aafc.subject',
              'title'     => 'aafcsubject',
              'content'   => $content,
            ],
          ];
          unset($page['#attached']['html_head'][$key]);
        }
      }
    }
  }

  if ($node) {
    $node = \Drupal::routeMatch()->getParameter('node');
    if (!$node) {
      return;
    }
    if (is_string($node)) {
      // Occurs when reverting to a previous version.
      return;
    }
    $type = '';
    $issued_date = '';
    $modified_date = '';
    if (!$node->hasField('field_issued')) {
      return;
    }
    if ($node->get('field_issued')->first()) {
      $issued_date = $node->get('field_issued')->first()->date->format('Y-m-d');
    }
    if ($node->get('field_modified')->first()) {
      $modified_date = $node->get('field_modified')->first()->date->format('Y-m-d');
    }

    if ($node->get('field_description')->first()) {
      $field_description_value = $node->get('field_description')->first()->getString();
    }
    if (isset($field_description_value)) {
      if (strlen($field_description_value) == strlen($summary)) {
        $summary_description = $field_description_value;
      }
      else {
        if (strpos($field_description_value, $summary) !== false) {
          $summary_description = $field_description_value;
        }
        else {
          $summary_description = $field_description_value . '; '. $summary;
        }
      }
    }
    else {
      $summary_description = $summary;
    }

    $dctermsdescription = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.description',
        'content'   => $summary_description,
      ],
    ];

    if (!isset($keywords)) {
      $keywords = [
        '#tag' => 'meta',
        '#attributes' => [
          'name'  => 'keywords',
          'title'     => 'keywords',
          'content'   => '',
        ],
      ];
    }

    if (!isset($aafcsubject)) {
      $aafcsubject = [
        '#tag' => 'meta',
        '#attributes' => [
          'name'  => 'aafc.subject',
          'title'     => 'aafcsubject',
          'content'   => '',
        ],
      ];
    }

    if (!isset($dctermstype)) {
      $dctermstype = [
        '#tag' => 'meta',
        '#attributes' => [
          'name'  => 'dcterms.type',
          'title'     => 'gctype',
          'content'   => '',
        ],
      ];
    }

    $dctermsissued = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.issued',
        'title'     => 'W3CDTF',
        'content'   => $issued_date,
      ],
    ];

    $dctermsmodified = [
      '#tag' => 'meta',
      '#attributes' => [
        'name'  => 'dcterms.modified',
        'title'     => 'W3CDTF',
        'content'   => $modified_date,
      ],
    ];

    $page['#attached']['html_head'][] = [$dctermsissued, 'dcterms.issued'];
    $page['#attached']['html_head'][] = [$dctermsmodified, 'dcterms.modified'];
    $page['#attached']['html_head'][] = [$aafcsubject, 'aafc.subject'];
    $page['#attached']['html_head'][] = [$dctermstype, 'dcterms.type'];
    $page['#attached']['html_head'][] = [$keywords, 'keywords'];
    $page['#attached']['html_head'][] = [$dctermsdescription, 'dcterms.description'];
  }

  $dctermsspatial = [
    '#tag' => 'meta',
    '#attributes' => [
      'name'  => 'dcterms.spatial',
      'title'     => 'gcregions',
      'content'   => '',
    ],
  ];

  $dctermsaudience = [
    '#tag' => 'meta',
    '#attributes' => [
      'name'  => 'dcterms.audience',
      'title'     => 'gcaudience',
      'content'   => '',
    ],
  ];

  $dctermsformat = [
    '#tag' => 'meta',
    '#attributes' => [
      'name'  => 'dcterms.format',
      'title'     => 'gcformat',
      'content'   => '',
    ],
  ];

  $page['#attached']['html_head'][] = [$dctermsaudience, 'dcterms.audience'];
  $page['#attached']['html_head'][] = [$dctermsformat, 'dcterms.format'];
  $page['#attached']['html_head'][] = [$dctermsspatial, 'dcterms.spatial'];

  return;
}



/**
 * Implements hook_form_node_form_alter().
 */
function wxt_overrides_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  /* set the default value for communictaion as meta data subject type */
  if ( $form_id == 'node_news_edit_form' ) {
    $communicationid = 38; // communication id =38
    $form['field_subject']['widget']['#options_attributes'][$communicationid] = ['checked' => 'checked'] ;
  }

  if ($form_id == 'node_landing_page_edit_form' || $form_id == 'node_page_edit_form'  ||
      $form_id == 'node_landing_page_form'      || $form_id == 'node_page_form'  ||
      $form_id == 'page-node-type-empl'  || $form_id == 'page-node-type-news' ) {
    // Cure warning about foreach argument must be of type array|object.
    $options = [];
    if (isset($form['menu']['link']['menu_parent']['#options'])) {
      $options = $form['menu']['link']['menu_parent']['#options'];
      if (is_null($options)) {
        // Cure warning about foreach argument must be of type array|object.
        $options = [];
      }
    }
    foreach ($options as $key => &$value) {
      $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
      if (isset($value) && $langcode == 'en' && strpos($value, 'disabled') == false) {
        $keyarray = explode (":", $key);
        if ( sizeof($keyarray) > 2) {
          if ( AgriAdminHelper::isLinkFrenchOnly($keyarray[2])) {
            unset($form['menu']['link']['menu_parent']['#options'][$key]);
          }
        }
      }
      else {
        if (isset($value) && $langcode == 'fr' && strpos($value, 'désactivé') == false) {
          $keyarray = explode (":", $key);
          if ( sizeof($keyarray) > 2) {
            if ( AgriAdminHelper::isLinkEnglishOnly($keyarray[2])) {
              unset($form['menu']['link']['menu_parent']['#options'][$key]);
            }
          }
        }
      }

      if (isset($value) && strpos($value, '-- ') == 0  ) {
          //$value =  substr($value,0, 3) . 'level 1. ' . substr( $value,3, strlen($value)) ;
        $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = ['class'=> 'menu_tree-leve-1'];
      }
      else {
        if (isset($value) && strpos($value, '---- ') == 0  ) {
          // $value =  substr($value,0, 5) . 'level 2. ' . substr( $value,5, strlen($value)) ;
          $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-2 glyphicon';
        }
        else {
          if (isset($value) && strpos($value, '------ ') == 0  ) {
            //$value =  substr($value,0, 7) . 'level 3. ' . substr( $value,7, strlen($value)) ;
            $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-3';
          }
          else {
            if (isset($value) && strpos($value, '-------- ') == 0  ) {
              //$value =  substr($value,0, 9) . 'level 4. ' . substr( $value,9, strlen($value)) ;
              $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-4';
            }
            else {
              if (isset($value) && strpos($value, '---------- ') == 0  ) {
                //$value =  substr($value,0, 11) . 'level 5. ' . substr( $value,11, strlen($value)) ;
                $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-5';
              }
              else {
                if (isset($value) && strpos($value, '------------ ') == 0  ) {
                  //$value =  substr($value,0, 13) . 'level 6. ' . substr( $value,11, strlen($value)) ;
                  $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-6';
                }
              }
            }
          }
        }
      }
    }
  }
  $entity = $form_state->getFormObject()->getEntity();
  $content_type = $entity->bundle();
  if ($content_type == 'page' || $content_type == 'landing_page' || $content_type == 'empl' || $content_type == 'news') {
    $other_lang = AgriAdminHelper::getOtherLang();
    if (isset($form['moderation_state']['widget'][0]['state']['#default_value'])) {
      $current_state = $form['moderation_state']['widget'][0]['state']['#default_value'];
      if ($current_state == 'published') {
        $form['moderation_state']['widget'][0]['state']['#default_value'] = 'draft';
        $form['moderation_state'][$other_lang]['widget'][0]['state']['#default_value'] = 'draft';
      }
    }
  }
}

/**
 * Implements hook_menu_alter().
 */
function wxt_overrides_link_alter(&$variables) {
  $url = $variables['url'];

  // Return early where possible.
  if (!$url->isRouted()) {
    return;
  }
  else {
    $route_name = $url->getRouteName();
    //$parent_route = $url->getParentRouteName();
    $current_route = \Drupal::routeMatch()->getRouteName();
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $moderated_default = $user->get('field_default_content_mode')->first();
    if (!empty($moderated_default)) {
      $moderated_default = $moderated_default->getValue()['value'];
    }
    else {
      $moderated_default = FALSE;
    }
    if ($current_route == 'system.admin_content' && $variables['text'] == 'Overview') {
      return;
    }
    else if ($current_route == 'content_moderation.admin_moderated_content' && $variables['text'] == 'Overview') {
      return;
    }
    else if ($variables['text'] == 'Overview') {
      return;
    }
    else if ($moderated_default && $route_name == 'system.admin_content' && $variables['text'] != 'Overview') {
      $link_options = $url->getOptions();
      if (isset($link_options['attributes']['class'][1])) {
        foreach ($link_options['attributes']['class'] as $key => $classname) {
          if ($classname === 'tabs__link') {
            return; // Do not manipulate this tabs__link as it is otherwise confusing to the end user.
          }
        }
      }
      $DEBUG = FALSE;
      if ($DEBUG && $fp = fopen('modules/custom/wxt_overrides/debug2.txt', 'a')) {
        fwrite($fp, print_r($url->getOptions(), TRUE) . "\n");
        fclose($fp);
      }
      $variables['text'] = t('Moderated content');
      $variables['url'] = \Drupal\Core\Url::fromUri('internal:/admin/content/moderated');
    }
    else if ($variables['text'] == 'Table') {
      return;
    }
    else if ($route_name == 'entity.media.collection') {
      $link_options = $url->getOptions();
      if ($current_route == 'entity.media.collection') {
        if (in_array('tabs__link', $link_options['attributes']['class'])) {
          return; // Do not manipulate this tabs__link as it is otherwise confusing to the end user.
        }
      }
      if (isset($link_options['attributes']['class']) && in_array('tabs__link', $link_options['attributes']['class']) && $variables['text'] == 'Table') {
        return; // Do not manipulate this tabs__link as it is otherwise confusing to the end user.
      }
      $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $variables['text'] = 'Media (grid)';
      if ($langcode == 'fr') {
        $variables['text'] = 'Médias (Grille)';
      }
      $variables['url'] = \Drupal\Core\Url::fromUri('internal:/admin/content/media-grid');
    }
  }
}

/**
 * Implements hook_form_comment_comment_form_alter().
 */
function wxt_overrides_form_comment_comment_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $blog_anon = \Drupal::config('wxt_overrides.settings')->get('blog_anon');
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if ($form_id == 'comment_comment_form') {
    $current_user = \Drupal::currentUser();
    $authenticated = $current_user->isAuthenticated();
    if ($authenticated && $blog_anon) {
      $form['#access'] = FALSE;
    }
    $roles = $current_user->getRoles();
    foreach ($roles as $role) {
      if (isset($form['field_my_name']['widget'][0])) {
        $form['field_my_name']['widget'][0]['#title'] = 'Your name';
        if ($langcode == 'fr') {
          $form['field_my_name']['widget'][0]['#title'] = 'Votre nom';
        }
      }
      if ($role == 'anonymous') {
        $form['author']['name']['#type'] = 'hidden';
        if ($langcode == 'en') {
          // echo print_r(array_keys($form), TRUE); die;
          $form['field_my_name']['widget'][0]['#default_value'] = '';
          $form['field_my_name']['widget'][0]['#placeholder'] = 'Anonymous';
          $form['author']['name']['#default_value'] = 'Anonymous';
        }
        else {
          $form['field_my_name']['widget'][0]['#default_value'] = '';
          $form['field_my_name']['widget'][0]['#placeholder'] = 'Anonyme';
          $form['author']['name']['#default_value'] = 'Anonyme';
        }
      }
      else {
        $form['field_my_name']['#disabled'] = TRUE;
      }
    }
  }
}

/** 
function wxt_overrides_cron() {
  $view = \Drupal\views\Views::getView('broken_links_report');
  $views_preview = $view->preview('data_export_1');
  $display = \Drupal::service('renderer')->renderRoot($views_preview);
  $directory = 'public://linkcheck';
  $file_system = \Drupal::service('file_system');
  $file_system->prepareDirectory($directory, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);
  $file_system->saveData($display, 'public://linkcheck/links.json', FileSystemInterface::EXISTS_REPLACE);
}
*/
