<?php

use Drupal\agri_admin\AgriAdminHelper;
/**
 * @file
 * Primary module hooks for WxT Overrides module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 *
 * Replace the wet-boew library v4.0.35 with v4.0.32 to each page.
 */
function wxt_overrides_page_attachments(array &$page) {
  $node = \Drupal::routeMatch()->getRawParameter('node');
  if (!isset($node)) {
    return;
  }
  if (is_object($node)) {
    $nid = $node->id();
  }
  if (is_string($node) || is_integer($node)) {
    $nid = $node;
  }
  if ($nid == 68 || $nid == 118) {
    $library_array = $page['#attached']['library'];
    if (in_array('wxt_library/wet-boew-dev', $page['#attached']['library'])) {
      $key = array_search('wxt_library/wet-boew-dev', $page['#attached']['library']);
      unset($page['#attached']['library'][$key]);
      $page['#attached']['library'][] = 'wxt_overrides/wet-boew-replacement';
    }
    if (in_array('wxt_library/wet-boew', $page['#attached']['library'])) {
      $key = array_search('wxt_library/wet-boew', $page['#attached']['library']);
      unset($page['#attached']['library'][$key]);
      $page['#attached']['library'][] = 'wxt_overrides/wet-boew-replacement';
    }
    $DEBUG = false;
    if ($DEBUG && $fp = fopen('modules/custom/wxt_overrides/js/wb/debug.txt', 'a'))
    {
      fwrite($fp, print_r($page, TRUE) . "\n");
      fclose($fp);
    }
  }
  return;
}



/**
 * Implements hook_form_node_form_alter().
 */
function wxt_overrides_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  /* set the default value for communictaion as meta data subject type */
  if ( $form_id == 'node_news_edit_form' ) {
    $communicationid = 38; // communication id =38
    $form['field_subject']['widget']['#options_attributes'][$communicationid] = ['checked' => 'checked'] ;
  }

  if ($form_id == 'node_landing_page_edit_form' || $form_id == 'node_page_edit_form'  ||
      $form_id == 'node_landing_page_form'      || $form_id == 'node_page_form'  ||
      $form_id == 'page-node-type-empl'  || $form_id == 'page-node-type-news' ) {

    foreach ($form['menu']['link']['menu_parent']['#options'] as $key => &$value) {
      $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $keyarray = explode (":", $key);
      if ( sizeof($keyarray) > 2) {
        $uuid = $keyarray[2];
        if ($langcode == 'en' && strpos($value, 'disabled') == false) {
          if ( AgriAdminHelper::isLinkFrenchOnly($uuid)) {
            AgriAdminHelper::addToLog($value);
            unset($form['menu']['link']['menu_parent']['#options'][$key]);
          }
        }
        else { 
          if ($langcode == 'fr' && strpos($value, 'désactivé') == false) {
            if ( AgriAdminHelper::isLinkEnglishOnly($uuid)) {
            unset($form['menu']['link']['menu_parent']['#options'][$key]);
            }     
          }
        }
      }
    
      if ( strpos($value, '-- ') == 0  ) {
          //$value =  substr($value,0, 3) . 'level 1. ' . substr( $value,3, strlen($value)) ;
        $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = ['class'=> 'menu_tree-leve-1'];
      }
      else {
        if ( strpos($value, '---- ') == 0  ) {
          // $value =  substr($value,0, 5) . 'level 2. ' . substr( $value,5, strlen($value)) ;
          $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-2 glyphicon';
        }
        else {
          if ( strpos($value, '------ ') == 0  ) {
            //$value =  substr($value,0, 7) . 'level 3. ' . substr( $value,7, strlen($value)) ;
            $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-3';
          }
          else {
            if ( strpos($value, '-------- ') == 0  ) {
              //$value =  substr($value,0, 9) . 'level 4. ' . substr( $value,9, strlen($value)) ;
              $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-4';
            }
            else {
              if ( strpos($value, '---------- ') == 0  ) {
                //$value =  substr($value,0, 11) . 'level 5. ' . substr( $value,11, strlen($value)) ;
                $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-5';
              }
              else {
                if ( strpos($value, '------------ ') == 0  ) {
                  //$value =  substr($value,0, 13) . 'level 6. ' . substr( $value,11, strlen($value)) ;
                  $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-6';
                }
              }
            }
          }
        }
      }
    } 
  }
}
