<?php

/**
 * @file
 * Primary module hooks for WxT Overrides module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 *
 * Replace the wet-boew library v4.0.35 with v4.0.32 to each page.
 */
function wxt_overrides_page_attachments(array &$page) {
  $library_array = $page['#attached']['library'];
  foreach ($library_array as $key => $value) {
    if ($value == 'wxt_library/wet-boew-dev') {
      unset($page['#attached']['library'][$key]);
    }
    if ($value == 'wxt_library/wet-boew') {
      unset($page['#attached']['library'][$key]);
    }
  }
  $page['#attached']['library'][] = 'wxt_overrides/wet-boew-replacement';
    $DEBUG = false;
    if ($DEBUG && $fp = fopen('modules/custom/wxt_overrides/js/wb/debug.txt', 'a'))
    {
      fwrite($fp, print_r($page, TRUE) . "\n");
      fclose($fp);
    }
  return;
}



/**
 * Implements hook_form_alter().
 *
 * 
 */
function wxt_overrides_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if ($form_id == 'node_landing_page_edit_form' || $form_id == 'node_page_edit_form'  ||
      $form_id == 'page-node-type-empl'  || $form_id == 'page-node-type-news' ) {

    foreach ($form['menu']['link']['menu_parent']['#options'] as $key => &$value) { 
      if ( strpos($value, '-- ') == 0  ) {
        //$value =  substr($value,0, 3) . 'level 1. ' . substr( $value,3, strlen($value)) ;
        $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = ['class'=> 'menu_tree-leve-1'];
      }
      else {
        if ( strpos($value, '---- ') == 0  ) {
         // $value =  substr($value,0, 5) . 'level 2. ' . substr( $value,5, strlen($value)) ;
          $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-2 glyphicon';
        }
        else {
          if ( strpos($value, '------ ') == 0  ) {
            //$value =  substr($value,0, 7) . 'level 3. ' . substr( $value,7, strlen($value)) ;
            $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-3';
          }
          else {
            if ( strpos($value, '-------- ') == 0  ) {
              //$value =  substr($value,0, 9) . 'level 4. ' . substr( $value,9, strlen($value)) ;
              $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-4';
            }
            else {
              if ( strpos($value, '---------- ') == 0  ) {
                //$value =  substr($value,0, 11) . 'level 5. ' . substr( $value,11, strlen($value)) ;
                $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-5';
              }
              else {
                if ( strpos($value, '------------ ') == 0  ) {
                  //$value =  substr($value,0, 13) . 'level 6. ' . substr( $value,11, strlen($value)) ;
                  $form['menu']['link']['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-6';
                }
              }  
            }
          }
        }
      }
    }
  }
}
