<?php

use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\Core\Entity\EntityInterface;
use Drupal\agri_admin\AgriAdminHelper;

/**
 * Implements hook_preprocess_html().
 */
function agri_admin_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $current_path = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  $variables['current_path'] = $current_path;
  $clean_path = preg_replace( '/[\W]/', '', $variables['current_path']);
  if (strlen($clean_path) > 30) {
    $clean_path = substr($clean_path, 0, 29);
  }
  if (strpos($current_path, 'node') > 0) {
    if (substr_compare($current_path, 'edit', -strlen('edit')) === 0) {
      $clean_path = 'node-edit';
    }
  }
  $variables['attributes']['class'][] = $clean_path;
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  foreach ($roles as $rolename) {
    $variables['attributes']['class'][] = 'role-is-' . $rolename;
  }
  $path = \Drupal::request()->getpathInfo();
  $arg  = explode('/',$path);
  if ($arg[0] == $langcode && isset($arg[2])) {
    $first_two_elements = $arg[1] . '-' . $arg[2];
  }
  if ($arg[1] == $langcode && isset($arg[3])) {
    $first_two_elements = $arg[2] . '-' . $arg[3];
  }
  if (isset($first_two_elements)) {
    $variables['attributes']['class'][] = $first_two_elements;
  }

}


/**
 * Implements hook_page_attachments().
 *
 * Adds the agri-admin libraries to each page.
 */
function agri_admin_page_attachments(array &$page) {
  $user = \Drupal::currentUser();
  if ($user->hasPermission('agrisource admin styles')) {
    $page['#attached']['library'][] = 'agri_admin/agri-admin';
  }
  return;
}

/**
 * Implements hook_theme()
 */
function agri_admin_theme($existing, $type, $theme, $path) {
  // Example of passing a variable to the theme (twig).
  return [
    'agri_admin' => [
      'variables' => ['test_var' => 'test value'],
    ],
  ];
}


/*variables array_keys=Array
(
    [0] => view
    [1] => rows
    [2] => title
    [3] => options
    [4] => context
    [5] => icon
    [6] => icon_position
    [7] => icon_only
    [8] => theme_hook_original
    [9] => attributes
    [10] => title_attributes
    [11] => content_attributes
    [12] => title_prefix
    [13] => title_suffix
    [14] => db_is_active
    [15] => is_admin
    [16] => logged_in
    [17] => user
    [18] => directory
    [19] => default_row_class
    [20] => #cache
)*/


/**
 * Implements hook_preprocess_views_view_field() for replacing current
 * revision field values with latest pending revision field values.
 * This is so we can have themed (orange as example) pending draft rows.
 * to complement the hotpink current draft rows.
 * @TODO: add {{ status }} to a view row.
 * May 14 2020: Added the implementation for customization on
 * Classfication Groups & Postion Title in Employment Opportunities View
 */
function agri_admin_preprocess_views_view_field(&$variables) {
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $view = $variables['view'];
  
  $hasPermission = FALSE;
  if ($variables['logged_in']) {
    $user = \Drupal::currentUser();
    $hasPermission = $user->hasPermission('agrisource pending drafts');
  }
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $otherLang = 'fr';
  if ($lang == 'fr') {
    $otherLang = 'en';
  }

  $view = $variables['view'];
  if ($hasPermission &&
       ($view->id() == 'news' ||
        $view->id() == 'view_employmentopportunities' ||
        $view->id() == 'view_news_work')) {
    $field = $variables['field'];
    $row = $variables['row'];
    $nid = $row->_entity->id();
    $vid = $row->_entity->getLoadedRevisionId();
    if ($row->_entity->isPublished() && $latestRevision = AgriAdminHelper::getLatestRevisionOnlyIfDraft($nid, $vid)) {
      if ($field->field == 'status') {
        //title
        //body
        //field_fieldname
        //status
        //nid
        //field_title
        $variables['output'] = strtolower($variables['output']);
        $variables['output'] = Drupal\Core\Render\Markup::create(str_replace('yes', 'no pending-draft', $variables['output']));
      } else if ($field->field == 'nothing') {
        // There is no fieldable field called 'nothing' this is a views field, so skip it.
        return;
      } else if ($field->field == 'machine_name') {
        // There is no fieldable field called 'machine_name', so skip it.
        return;
      } else if ($field->field == 'nid') {
        // There is no fieldable field called 'nid', so skip it.
        return;
      } else if ($field->field == 'tid') {
        // There is no fieldable field called 'tid', so skip it.
        return;
      } else {
        $valueCurrent = '';
        if ($lang == 'fr') {
          $valueCurrent = $row->_entity->getTranslation($lang)->get($field->field)->value;
        } else {
          $valueCurrent = $row->_entity->get($field->field)->value;
        }
        $valuePending = $latestRevision->get($field->field)->value; // Already in current language.
        // Replace characters in the field output.
        $variables['output'] = Drupal\Core\Render\Markup::create(str_replace($valueCurrent, $valuePending, $variables['output']));
        if ($field->field == 'title' || $field->field == 'field_title') {
          $alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/'.$nid);
          $urlPathToLatest = '/node/' . $nid . '/latest';
          // Replace path to node in the field output.
          $variables['output'] = Drupal\Core\Render\Markup::create(str_replace($alias, $urlPathToLatest, $variables['output']));
        }
      }
      // If the above code is crashing, move the debug code higher above and enable it/refactor the debug code.
      $DEBUG = FALSE;
      if ($DEBUG && $fp = fopen('debug.txt', 'a'))
      {
        fwrite($fp, 'debug=NID=' . $nid . ' ' . print_r(' test', TRUE) . "\n");
        fwrite($fp, 'debug=test=' . $nid .print_r($field->field, TRUE) . "\n");
        //fwrite($fp, 'debug=status=' . $nid .print_r(get_object_vars($row->_entity), TRUE));
        //fwrite($fp, 'debug=object_vars=' . $nid .print_r(get_object_vars($row->_entity), TRUE));
        //fwrite($fp, 'debug row methods='.print_r(get_class_methods($variables['row']), TRUE));
        //fwrite($fp, 'debug entity methods='.print_r(get_class_methods($row->_entity), TRUE) . "\n");
        fclose($fp);
      }
    }
  }

  if ($view->id() == 'view_employmentopportunities') {
    $field = $variables['field'];
    $row = $variables['row'];
    $node = $row->_entity;
    $classification   = '';
    if ($field->field =='field_classification' && $node->getType() == 'empl') {
     // if ($row->_entity->get($field->field)->value) {
      if ($paragraph_field_items =  $row->_entity->get('field_classification')->getValue()) {
        $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');
        // Collect paragraph field's ids.
        $ids = array_column($paragraph_field_items, 'target_id');
        // Load all paragraph objects.
        $paragraphs_objects = $paragraph_storage->loadMultiple($ids);
        foreach ($paragraphs_objects as $paragraph) {
          // Get field from the paragraph.
          $groupval    = $paragraph->get('field_class_id')->value;
          $subgroupval = $paragraph->get('field_class_sub')->value;
          $levelval    = $paragraph->get('field_class_level')->value;
          $tmpText     = '';
          // Do something with $text...
          if ($subgroupval) {
            $tmpText = $groupval.'-'.$subgroupval.'-'.$levelval;
          }
          else {
            $tmpText = $groupval.'-'.$levelval;
          }
          if ( strlen($classification) >0 ) {
            $classification = $classification.', '. $tmpText;
          }
          else {
            $classification = $tmpText;
          }
        }
        $ptitle = $row->_entity->get('title')->value;
        // Friendly url explained: https://drupal.stackexchange.com/a/275438/99288 .
        $friendly_url = $node->toUrl()->toString(); // Relative url.
        //$friendly_url = $node->toUrl()->setAbsolute()->toString(); // Or absolute url.
        // @Note to James, previously, $nid was undefined, so this was producing an invalid link.
        // So I changed it to the friendly url instead as a fix and improvement.
        $titlefield = '<a href="'.$friendly_url.'"'. ' hreflang="'.$lang.'">'. $node->get('title')->value.'</a>';
        $variables['output'] =  \Drupal\Core\Render\Markup::create( $classification.' '. $titlefield);
      }
    }

  }
}


/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function agri_admin_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  $entity_id = $entity->id();

  $action = 'insert';
  AgriAdminHelper::addToLog(__function__);
  drupal_register_shutdown_function('_helperUpdateProcess', $action, $entity_id, $entity->bundle());
  drupal_register_shutdown_function('_helperLockingContent', $action, $entity_id, $entity->bundle(), $entity);
}


/**
 * Implements hook_ENTITY_TYPE_update().
 */
function agri_admin_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  $entity_id = $entity->id();


  $action = 'update';
//  AgriAdminHelper::addToLog(__function__);
//  AgriAdminHelper::addToLog(print_r($DEBUG_THIS, TRUE), TRUE);
  drupal_register_shutdown_function('_helperUpdateProcess', $action, $entity_id, $entity->bundle());
  drupal_register_shutdown_function('_helperLockingContent', $action, $entity_id, $entity->bundle(), $entity);
}


/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function agri_admin_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  // Custom code goes here:
  $entity_id = $entity->id();
  // Set Authored by to current user if role is creator except during Peer Review.
  $current_author_id = $entity->getOwnerId();
  $current_user = \Drupal::currentUser();
  $current_user_id = $current_user->id();
  $roles = $current_user->getRoles();
  $authored_on = $entity->getCreatedTime();
  $content_type = $entity->bundle();

  if ($content_type == 'page' || $content_type == 'landing_page') {
    $peer_review_status = $entity->get('field_peer_review')->getString();      
    $changed_time = $entity->getChangedTime();
    $date_issued = $entity->get('field_issued')->getString();
    $date_modified = $entity->get('field_modified')->getString();
    $update_date_modified_str = $entity->get('field_update_date_modified')->getString();
    $moderation_state = $entity->moderation_state->value;
    $created_by = $entity->get('field_created_by')->getString();
//    AgriAdminHelper::addToLog(print_r('Current: '.$current_user, TRUE), TRUE);

    if (empty($created_by)) {
      if ($entity->isNew()) {
        $entity->set('field_created_by', $current_user->getUsername());      
      } else {
        $admin_username = \Drupal\user\Entity\User::load(1)->getUsername();
        $entity->set('field_created_by', $admin_username);
      }
    }

    if ($moderation_state == 'published') {
      $dt = new DateTime();
      if (empty($date_issued)) {
        $entity->set('field_issued', $dt->format('Y-m-d'));
      }

      if ($update_date_modified_str == '0') {
	$entity->set('changed', strtotime($date_modified));
      } 
      else {
        $entity->set('field_modified', $dt->format('Y-m-d'));
      }
    }

    if ($moderation_state == 'published' || $moderation_state == 'archived') {
      $entity->set('field_peer_review', '');
    }
//    AgriAdminHelper::addToLog($debug_message, TRUE);
  }

  foreach ($roles as $value) {
    $role = $value;
    if (($role == 'creator' &&  empty($peer_review_status)) || $role == 'news_ccpub' || $role == 'empl_cspub') {
//AgriAdminHelper::addToLog('presave called for ' . $entity->language()->getId() . ' ' . $entity->id(), TRUE);
      $langcode = $entity->language()->getId();
      if ($langcode == 'en') {
        $entity->getTranslation('fr')->setOwnerId($current_user_id);
      }
      else {
        $entity->getTranslation('en')->setOwnerId($current_user_id);
      }
      $entity->setOwnerId($current_user_id);
      $entity->set('created', time());
    }
  }

}


function _helperLockingContent($action, $entity_id, $bundle, $entity_obj = NULL) {
  global $import_override;
  if (!isset($import_override) || $import_override == FALSE) {
    if ($action == 'insert' || $action == 'update') {
      $current_user = \Drupal::currentUser();
      $current_user_id = $current_user->id();
      if ($action == 'update') {
        $latest = $entity_obj; //AgriAdminHelper::getLatestRevision($entity_id, $vid);
      }
      if ($action == 'insert') {
        $latest = $entity_obj;
      }
      $current_author_id = $latest->getOwnerId();
      if (!isset($current_author_id)) {
        $current_author_id = $current_user_id;
      }

      $lock_service = \Drupal::service('content_lock');
      $is_creator = FALSE;
      $is_master = FALSE;
      $is_reviewer = FALSE;
      $roles = $current_user->getRoles();
      foreach ($roles as $value) {
        $role = $value;
        if ($role == 'news_ccpub' || $role == 'empl_cspub') {
          $is_master = TRUE;
          $state = $latest->get('moderation_state')->getString();
          if ($state == 'draft' || $state == 'review_by_reviewer' || $state == 'author_reviewing') {
            $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
            return; // Finished processing.
          }
          else {
            $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
          }
        }
        if ($role == 'creator') {
          $is_creator = TRUE;
	  $state = $latest->get('moderation_state')->getString();
	  $peer_review_status = $latest->get('field_peer_review')->getString();
          if ($state == 'draft' && empty($peer_review_status)) {
            $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
            return; // Finished processing.
          }
          else {
            $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
          }
        }
        if ($role == 'reviewer' && $state == 'with_reviewer') {
          $is_reviewer = TRUE;
          // Persist the lock for the reviewer.
          $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
          return; // Finished processing.
        }
      }
      // $original_state = $entity_obj->getOriginal('moderation_state')->getString();
      $state = $latest->get('moderation_state')->getString();
      if ($state == 'review_by_reviewer' && !$is_creator && !is_null($entity_obj)) {
        // @TODO for Deepani - Call a function that sends an email to the reviewer role.
        // @TODO Check the content type of $latest (entity) and do a case, possibly different group email per content type.
      }
      if ($state == 'author_reviewing' && !$is_creator && !is_null($entity_obj)) {
        // Reviewer is rejecting, sends back to author_reviewing, re-assigns the lock to the $current_author_id.
        $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
        // @TODO for Deepani - Call a function that sends an email to $current_author_id (get his email address) and send email.
      }
      else if (!$is_creator) {
        // Is neither reviewer, nor creator, therefore release all locks.
        $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
        $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
      }
    }
  }
}

function _helperUpdateProcess($action, $entity_id, $bundle) {
  global $import_override;
  if (!isset($import_override) || $import_override == FALSE) {
    AgriAdminHelper::addToLog('_helperUpdateProcess action=' . $action . ' : ' . $entity_id . ' : ' . $bundle);
    $menu_link_ids = [];
    $menu_link_ids = AgriAdminHelper::postCreateOrUpdateAutoTranslate($action, $entity_id, $bundle);
    //AgriAdminHelper::postUpdateProcess($action, $entity_id, $bundle);
    if ($bundle == 'page') {
      AgriAdminHelper::disableMenuLink(NULL, $entity_id, 'main', TRUE);
      AgriAdminHelper::disableMenuLink(NULL, $entity_id, 'sidebar');
    }
  }
}


/**
 * Implements hook_form_form_views_form_newsatworkbulletin_page_1_alter().
 */
function agri_admin_form_views_form_newsatworkbulletin_page_1_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'agri_admin/news-at-work-bulletin'; // For empl submit.
}

/**
 * Implements hook_form_node_news_form_alter().
 */
function agri_admin_form_node_news_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::currentUser()->isAnonymous()) {
    // Remove/do not render these form elements from anonymous user.
    $form['revision_log']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
    $form['revision']['#access'] = FALSE;
    $form['field_keywords']['#access'] = FALSE;
    $form['field_description']['#access'] = FALSE;
    $form['moderation_state']['#access'] = FALSE;
    // End of remove these form elements from anonymous user:

    $form['actions']['preview']['#weight'] = -99;
    // See js/agri-empl-or-news-submit.js previewInNewTab().
    $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit_css'; // For empl submit.
    $form['actions']['#weight'] = 10;
    $form['actions']['submit']['#value'] = t('Submit'); 
    //$form['#attributes']['target'] = '_blank';
    //$form['#attributes']['novalidate'] = 'novalidate';
  }
}

/**
 * Implements hook_form_node_empl_form_alter().
 */
function agri_admin_form_node_empl_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::currentUser()->isAnonymous()) {
    // Remove/do not render these form elements from anonymous user.
    $form['revision_log']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;

// $debug_this = $form['field_classification'];
//AgriAdminHelper::addToLog('classif debug: <pre>' . print_r(array_keys($debug_this),TRUE) . '</pre>' , TRUE);

    $form['revision']['#access'] = FALSE;
    $form['field_keywords']['#access'] = FALSE;
    $form['field_description']['#access'] = FALSE;
    $form['moderation_state']['#access'] = FALSE;
    // End of remove these form elements from anonymous user:

    $form['actions']['preview']['#weight'] = -99;
    // See js/agri-empl-or-news-submit.js previewInNewTab().
    $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit_css'; // For empl submit.
    $form['actions']['#weight'] = 5;
    $form['actions']['submit']['#value'] = t('Submit Request');
    //$form['#attributes']['target'] = '_blank';
    //$form['#attributes']['novalidate'] = 'novalidate';
  }
}


/**
 * Implements hook_form_node_form_alter().
 */
function agri_admin_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();
  $content_type = $entity->bundle();
  if ($content_type == 'page' || $content_type == 'landing_page') {
    $form['field_issued']['widget'][0]['#disabled'] = TRUE;
    $form['field_modified']['widget'][0]['#disabled'] = TRUE;
    $form['field_created_by']['widget'][0]['#disabled'] = TRUE;
    $form['field_dc_date_created']['widget'][0]['#disabled'] = TRUE;
    $form['#attached']['library'][] = 'agri_admin/page'; // For page and landing page edit/add css.

//  AgriAdminHelper::addToLog($debug_message, TRUE);
//Copying fields to label:
    if (isset($form['field_dc_date_created']['widget'][0])) {
      $date_created_date = $form['field_dc_date_created']['widget'][0]['value']['#default_value'];
      if (is_object($date_created_date)) {
        $form['field_dc_date_created']['widget'][0]['value']['#title'] = t('dc.date.created') . ': ' . $date_created_date->format('Y-m-d');
      }
      else {
        $form['field_dc_date_created']['widget'][0]['value']['#title'] = t('dc.date.created') . ':';
      }
      $form['field_dc_date_created']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_created_by']['widget'][0])) {
      $created_by = $form['field_created_by']['widget'][0]['value']['#default_value'];
      if (!empty($created_by)) {
        $form['field_created_by']['widget'][0]['value']['#title'] = t('Created by') . ': ' . $created_by;
      }
      else {
        $form['field_created_by']['widget'][0]['value']['#title'] = t('Created by') . ':';
      }
      $form['field_created_by']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_issued']['widget'][0])) {
      $date_issued = $form['field_issued']['widget'][0]['value']['#default_value'];
      if (is_object($date_issued)) {
        $form['field_issued']['widget'][0]['value']['#title'] = t('dcterms:issued') . ': ' . $date_issued->format('Y-m-d');
      }
      else {
        $form['field_issued']['widget'][0]['value']['#title'] = t('dcterms:issued') . ':';
      }
      $form['field_issued']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_modified']['widget'][0])) {
      $date_modified = $form['field_modified']['widget'][0]['value']['#default_value'];
      if (is_object($date_modified)) {
        $form['field_modified']['widget'][0]['value']['#title'] = t('dcterms:modified') . ': ' . $date_modified->format('Y-m-d');
      }
      else {
        $form['field_modified']['widget'][0]['value']['#title'] = t('dcterms:modified') . ':';
      }
      $form['field_modified']['#attributes']['class'] = 'hidden-input-box';
    }

    $moderation_state = $entity->moderation_state->value;
    $peer_review_status = $entity->get('field_peer_review')->getString();

    if ($entity->isNew()) {
      $form['field_peer_review']['#disabled'] = TRUE;
    } 
    elseif ($moderation_state == 'published' || $moderation_state == 'archived') {
        $form['field_peer_review']['#disabled'] = TRUE;
        $form['field_tracking_number']['widget'][0]['value']['#default_value'] = '';
    } 
    elseif ($moderation_state == 'draft' &&  empty($peer_review_status)) {
      // Do not enable peer reviewed.
      $form['field_peer_review']['widget']['#options_attributes']['peer_reviewed']['disabled'] = 'disabled';
    }
  }// End page/landing_page.
}


/**
 * Implements hook_system_breadcrumb_alter().
 * for /node/add/news page
 */
function agri_admin_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  $previousUrl = \Drupal::request()->server->get('HTTP_REFERER');
  $node = \Drupal::routeMatch()->getParameter('node_preview');
  if ($node) { 
    $nType = $node->getType(); 
  }
  if (isset($breadcrumb)) {
    $links = $breadcrumb->getlinks();
    if (is_array($links) && isset($links[0])) {
      $first_breadcrumb_text = $links[0]->getText();
      if ($first_breadcrumb_text == 'Agrisource') {
        // Make sure that the first breadcrumb link starts with 'Home' instead of 'Agrisource'.
        $links[0]->setText(t('Home'));
      }
    }
  }

  //handle /node/preview page for News
  if (((strpos($result,'/node/preview/') !==false) && ($nType == 'news'))
    && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new \Drupal\Core\Breadcrumb\Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // dynamically handle the route name for News link
      $news = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->condition('title', 'news', '=')
        ->execute();
      if ($news) {
        $langcode = \Drupal\agri_admin\AgriAdminHelper::getLang();
        if (is_array($news)) {
          $first_nid = array_shift($news);
          $news = \Drupal\node\Entity\Node::load($first_nid);
        }
        if ($news->hasTranslation($langcode)) {
          $news = $news->getTranslation($langcode);
        }
        $linkNews = $news->toLink($news->getTitle());
      }
      else {
        $linkNews = Link::createFromRoute(t('News'), 'view.view_news_work.page_1');
      }
      $breadcrumb->addLink($linkNews);
    }
  }

  // handle /node/preview page for Employment Opportunity form
  if (((strpos($result,'/node/preview/') !==false) && ($nType == 'empl'))
    && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks(); 
      $breadcrumb = new \Drupal\Core\Breadcrumb\Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // dynamically handle the route name for EO link
      $hr = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->condition('title', 'Human Resources – Services and Information', '=')
        ->execute();
      if ($hr) {
        $langcode = \Drupal\agri_admin\AgriAdminHelper::getLang();
        if (is_array($hr)) {
          $first_nid = array_shift($hr);
          $hr = \Drupal\node\Entity\Node::load($first_nid);
        }
        if ($hr->hasTranslation($langcode)) {
          $hr = $hr->getTranslation($langcode);
        }
	$linkHR = $hr->toLink(t('Human Resources'));
      }
      else {
        $linkHR = Link::createFromRoute(t('Human Resources'), 'view.view_employmentopportunities.page_1');
      }
      $breadcrumb->addLink($linkHR); 
    }
  }

  if (($result =='/node/add/news') && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new \Drupal\Core\Breadcrumb\Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // dynamically handle the route name for News link
      $news = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->condition('title', 'news', '=')
        ->execute();
      if ($news) {
        $langcode = \Drupal\agri_admin\AgriAdminHelper::getLang();
        if (is_array($news)) {
          $first_nid = array_shift($news);
          $news = \Drupal\node\Entity\Node::load($first_nid);
        }
        if ($news->hasTranslation($langcode)) {
          $news = $news->getTranslation($langcode);
        }
	$linkNews = $news->toLink($news->getTitle());
      }
      else {
        $linkNews = Link::createFromRoute(t('News'), 'view.view_news_work.page_1');
      }
      $breadcrumb->addLink($linkNews);
      //Dynamically handle the route name for news at work link
      $news_at_work = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->condition('title', 'news@work', '=')
        ->execute();
      if (is_array($news_at_work)) {
        $first_nid = array_shift($news_at_work);
        $news_at_work = \Drupal\node\Entity\Node::load($first_nid);
      }
      if ($news_at_work) {
        $langcode = \Drupal\agri_admin\AgriAdminHelper::getLang();
        if ($news_at_work->hasTranslation($langcode)) {
          $news_at_work = $news_at_work->getTranslation($langcode);
        }
	$linkNewsatWork = $news_at_work->toLink($news_at_work->getTitle());
      }
      else {
        $linkNewsatWork = Link::createFromRoute(t('News@work'), 'view.view_news_work.page_1');
      }   
      $breadcrumb->addLink($linkNewsatWork);
    }
  }

  if (($result =='/node/add/empl') && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new \Drupal\Core\Breadcrumb\Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // dynamically handle the route name for HR link
      $hr = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->condition('title', 'Human Resources – Services and Information', '=')
       ->execute();
      if ($hr) {
        $langcode = \Drupal\agri_admin\AgriAdminHelper::getLang();
        if (is_array($hr)) {
          $first_nid = array_shift($hr);
          $hr = \Drupal\node\Entity\Node::load($first_nid);
        }
        if ($hr->hasTranslation($langcode)) {
          $hr = $hr->getTranslation($langcode);
        }
	$linkHR = $hr->toLink(t('Human Resources'));
      }
      else {
        $linkHR = Link::createFromRoute(t('Human Resources'), 'view.view_employmentopportunities.page_1');
      }
      $breadcrumb->addLink($linkHR);
      $staffing = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->condition('title', 'Staffing', '=')
        ->execute();
      if (is_array($staffing)) {
        $first_nid = array_shift($staffing);
        $staffing = \Drupal\node\Entity\Node::load($first_nid);
      }
      if ($staffing) {
        $langcode = \Drupal\agri_admin\AgriAdminHelper::getLang();
        if ($staffing->hasTranslation($langcode)) {
          $staffing = $staffing->getTranslation($langcode);
        }
	$linkStaffing = $staffing->toLink($staffing->getTitle());
      }
      else {
        $linkStaffing = Link::createFromRoute(t('Staffing'), 'view.view_employmentopportunities.page_1');
      } 
      $breadcrumb->addLink($linkStaffing);
    }
  }
}

/**
 * Implements hook_preproces_breadcrumb.
 * for /node/add/news page
 */
function agri_admin_preprocess_breadcrumb(&$variables) {
  if ($variables['breadcrumb']) {
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
    $current_path = \Drupal::service('path.current')->getPath();
    $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
 
    if (!empty($page_title) && ($result =='/node/add/news') && (\Drupal::currentUser()->isAnonymous())) {
      $variables['breadcrumb'][] = [
        'text' => t('Submit an article for news at work'),
        'attributes' => new Drupal\Core\Template\Attribute(['class' => ['active']])
      ];
    }

    if (!empty($page_title) && ($result =='/node/add/empl') && (\Drupal::currentUser()->isAnonymous())) {
      $variables['breadcrumb'][] = [
        'text' => t('Internal Employment Opportunity Request Form'),
        'attributes' => new Drupal\Core\Template\Attribute(['class' => ['active']])
      ];
    }
  }
}


/**
 * Implements hook_preprocess_HOOK().
 */

function agri_admin_preprocess_field_multiple_value_form(&$vars) {
  if (!\Drupal::currentUser()->isAnonymous()) { return; }
  // Anonymous only logic below.

  // Remove weight option for multivalue fields.
  if (isset($vars['table']['#tabledrag'])) {
    unset($vars['table']['#tabledrag']);
    array_pop($vars['table']['#header']);
    foreach ($vars['table']['#rows'] as &$row) {
      foreach ($row['data'] as $key => $rowrowdata) {
        if (!$rowrowdata['data']) {
          unset($row['data'][$key]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_fieldset_HOOK().
 */

function agri_admin_preprocess_fieldset(&$variables) {
  unset($variables['attributes']['required']);
  unset($variables['attributes']['aria-required']);
  unset($variables['attributes']['aria-invalid']);
}

/**
 * Implements hook_preprocess_select_HOOK().
 */

function agri_admin_preprocess_select(&$variables) {
  if (!isset($variables['element']['#field_name'])) { return; }
  if (\Drupal::currentUser()->isAnonymous()) {
    if ($variables['element']['#field_name']) {
      if ($variables['element']['#field_name']== 'field_newstype') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_to') {
        $variables['attributes']['size'] = 1;
      } 

      if ($variables['element']['#field_name']== 'field_branch') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name']== 'field_class_id') {
        $variables['attributes']['size'] = 1;
      }
  
      if ($variables['element']['#field_name']== 'field_class_sub') {
        $variables['attributes']['size'] = 1;
      } 
  
      if ($variables['element']['#field_name']== 'field_class_level') {
        $variables['attributes']['size'] = 1;
      }
    }
  }
}

/**
 * Implements hook_preprocess_form_element_label_HOOK().
 */

function agri_admin_preprocess_form_element_label(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if ($variables['attributes']['for']) { 
      if ($variables['attributes']['for'] == 'edit-advanced' ) {
        // This squelches w3c error for label that has no element.
        // Since we have removed edit-advanced section we also adjust its label.
        unset($variables['element']);
        unset($variables['attributes']['for']);
        unset($variables['attributes']['class']);
        $variables['attributes']['class'] = 'sr-only';
      }  
    }
  }
}

/**
 * Implements hook_content_moderation_notification_mail_data_alter().
 */
function agri_admin_content_moderation_notification_mail_data_alter(Drupal\Core\Entity\EntityInterface $entity, array &$data) {
  $entitiyLang = $entity->get('langcode')->value;
  //avoid sending two emails for the same entity (en and fr) since the French information will be included in the English email
  if ($entitiyLang == 'en'){
    $currentModState = $entity->get('moderation_state')->getString();
    $nType = $entity->bundle();
    if ($nType == 'news'){
      if ($currentModState == 'draft'){
        $newsSubmitterEmail = $entity->get('field_newssubmitteremail')->value;
        //TODO - replace deepaniw@hotmail.com with aafc.newsatwork-nouvellesalouvrage.aac@canada.ca and ccpub group
        $data['to'] = ['deepaniw@hotmail.com', $newsSubmitterEmail];
      }
      else {
        $data['to'] = [];
      }      
    }
    elseif ($nType == 'empl'){
      if ($currentModState == 'draft'){
        $emplSubmitterEmail = $entity->get('field_employmentrequestoremail')->value;
        //TODO - replace deepaniw@hotmail.com with aafc.hrcentrerh.aac@canada.ca and cspub group
        $data['to'] = ['deepaniw@hotmail.com', $emplSubmitterEmail];
        $emplMessage = "<p>Le français suit</p>
                        <p>Your request ". "\""."[agri-admin:title]" ."\"". " has been submitted and will be processed for publication on AgriSource by Human Resources within 2 working days.</p>" .
                        "<p>To preview this opportunity, visit:&nbsp; [agri-admin:url]</p>" . 
                        "<p>If you have any questions or concerns, please contact your&nbsp;<a data-auth='NotApplicable' 
                        href='http://intranet.agr.gc.ca/agrisourceprev/AgriDoc.do?id=1548432&amp;lang=eng' rel='noopener noreferrer' 
                        target='_blank'>Human Resource Advisor, Staffing.</a>
                        <hr />
                        <p>Votre demande relative à la possibilité d'emploi «&nbsp;[agri-admin:translation-title]&nbsp;» a été présentée et sera traitée aux fins de publication dans AgriSource par les Ressources humaines dans les deux jours ouvrables.</p>
                        <p>Pour voir un aperçu de cette possibilité, consultez&nbsp;:&nbsp; [agri-admin:translation-url]</p>" .
                        "<p>Pour toute question ou préoccupation, veuillez communiquer avec votre&nbsp;<a data-auth='NotApplicable' 
                        href='http://intranet.agr.gc.ca/agrisourceprev/AgriDoc.do?id=1548428&amp;lang=fra' rel='noopener noreferrer'
                        target='_blank'>conseiller(ère) en ressources humaines responsable de la dotation.</a>";
                          
        $data['params']['subject'] = "Your employment opportunity " . "\"" . "[node:title]" . "\"" ." request has been submitted / Votre demande relative à la possibilité d'emploi «&nbsp;[agri-admin:translation-title]&nbsp;» a été présentée.";
        $data['params']['message'] = check_markup($emplMessage, 'full_html');
      }
      else {
        $data['to'] = [];
      }      
    }
    //For basic and landing page CT, default email list will be used when publishing happens and no emails will be sent when drafts are created
    else {
      if ($currentModState == 'draft'){
        $data['to'] = [];
      }      
    }
  }
  if ($entitiyLang == 'fr'){
    $data['to'] = [];
  }
}

/**
 * Implements hook_token_info().
 */
function agri_admin_token_info() {
  $info = [];
  $info['types']['agri-admin'] = ['name' => t('Custom Group'), 'description' => t('Custom Group to use in content moderation notification emails')];
  $info['tokens']['agri-admin']['translation-title'][] = 'A token to extract the translated node title';
  $info['tokens']['agri-admin']['translation-url'][] = 'A token to extract the translated URL';
  $info['tokens']['agri-admin']['title'][] = 'A token to extract the current title for news and employment opportunity when using submission form';
  $info['tokens']['agri-admin']['url'][] = 'A token to extract the current URL for news and employment opportunity when using submission form';
  return $info;
}

/**
 * Implements hook_tokens().
 */
function  agri_admin_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if(isset($data['entity'])){
    $entity = $data['entity'];
    if ($entity instanceof \Drupal\node\NodeInterface) {
      $translated_entity = $entity->getTranslation('fr');
      $translated_title = $translated_entity->getTitle();
      $translated_url = $translated_entity->toLink()->toString();
      $current_title = $entity->getTitle();
      $current_url = $entity->toLink()->toString();      
      if ($type == 'agri-admin') {
        foreach ($tokens as $name => $original) {
          // Find the desired token by name.
          switch ($name) {
            case 'translation-title':
              $replacements[$original] = $translated_title;
              break;
            case 'translation-url':
              $replacements[$original] = $translated_url;
              break;
            case 'title':
              $replacements[$original] = $current_title;
              break;
            case 'url':
              $replacements[$original] = $current_url;
              break;
          }
        }
      }
    }
  }
  return $replacements;
}


/**
 * Implements hook_form_FORM_ID_alter.
 */

function agri_admin_form_menu_link_content_menu_link_content_form_alter (&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id = 'menu_link_content_menu_link_content_form') {
    //AgriAdminHelper::addToLog('form_id ' . $form_id, TRUE);
    $form['#attached']['library'][] = 'agri_admin/menu-navigation-hide-disabled'; // For hiding disabled items adding checkbox.
  }
  foreach ($form['menu_parent']['#options'] as $key => &$value) {
    if ( strpos($value, '-- ') == 0  ) {
      //$value =  substr($value,0, 3) . 'level 1. ' . substr( $value,3, strlen($value)) ;
      $form['menu_parent']['#options_attributes'][$key]['class'] = ['class'=> 'menu_tree-leve-1'];
    }
    else {
      if ( strpos($value, '---- ') == 0  ) {
        // $value =  substr($value,0, 5) . 'level 2. ' . substr( $value,5, strlen($value)) ;
        $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-2 glyphicon';
      }
      else {
        if ( strpos($value, '------ ') == 0  ) {
          //$value =  substr($value,0, 7) . 'level 3. ' . substr( $value,7, strlen($value)) ;
          $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-3';
        }
        else {
          if ( strpos($value, '-------- ') == 0  ) {
            //$value =  substr($value,0, 9) . 'level 4. ' . substr( $value,9, strlen($value)) ;
            $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-4';
          }
          else {
            if ( strpos($value, '---------- ') == 0  ) {
              //$value =  substr($value,0, 11) . 'level 5. ' . substr( $value,11, strlen($value)) ;
              $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-5';
            }
            else {
              if ( strpos($value, '------------ ') == 0  ) {
                //$value =  substr($value,0, 13) . 'level 6. ' . substr( $value,11, strlen($value)) ;
                $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-6';
              }
            }
          }
        }
      }
    }
  }
}
