<?php

/**
 * @file
 * Admin functionality (mostly) custom module for aafc.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\media\Entity\Media;
use Drupal\node\NodeInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Entity\EntityInterface;
use Drupal\agri_admin\AgriAdminHelper;
use Drupal\agri_admin\Utils;
use Drupal\Core\Database\Database;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\user\Entity\User;
use Drupal\views\ViewExecutable;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Site\Settings;
use Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\Core\Render\Markup;
use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_html().
 */
function agri_admin_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $current_path = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $variables['current_path'] = $current_path;
  $clean_path = preg_replace('/[\W]/', '', $variables['current_path']);
  if (strlen($clean_path) > 30) {
    $clean_path = substr($clean_path, 0, 29);
  }
  if (isset($current_path) && strpos($current_path, 'node') > 0) {
    if (substr_compare($current_path, 'edit', -strlen('edit')) === 0) {
      $clean_path = 'node-edit';
    }
  }
  $variables['attributes']['class'][] = $clean_path;
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  foreach ($roles as $rolename) {
    $variables['attributes']['class'][] = 'role-is-' . $rolename;
  }
  $path = \Drupal::request()->getpathInfo();
  $arg  = explode('/', $path);
  if ($arg[0] == $langcode && isset($arg[2])) {
    $first_two_elements = $arg[1] . '-' . $arg[2];
  }
  if ($arg[1] == $langcode && isset($arg[3])) {
    $first_two_elements = $arg[2] . '-' . $arg[3];
  }
  if (isset($first_two_elements)) {
    $variables['attributes']['class'][] = $first_two_elements;
  }

}

/**
 * Implements hook_page_attachments().
 *
 * Adds the agri-admin libraries to each page.
 */
function agri_admin_page_attachments(array &$page) {
  $user = \Drupal::currentUser();
  if ($user->hasPermission('agrisource admin styles')) {
    $page['#attached']['library'][] = 'agri_admin/agri-admin';
    $current_route = \Drupal::routeMatch()->getRouteName();
    if ($current_route == 'content_moderation.admin_moderated_content' || $current_route == 'system.admin_content') {
      global $base_url;
      $page['#attached']['drupalSettings']['agrisource']['base_url'] = $base_url;
      $page['#attached']['library'][] = 'agri_admin/legacy-support';
      $page['#attached']['library'][] = 'agri_admin/content-plugins-changes';
      $page['#attached']['drupalSettings']['agrisource']['show_restricted_plugins_permissions'] = $user->hasPermission('agrisource show restricted plugins');
    }
  }
}

/**
 * Implements hook_theme().
 */
function agri_admin_theme($existing, $type, $theme, $path) {
  // Example of passing a variable to the theme (twig).
  return [
    'agri_admin' => [
      'variables' => ['test_var' => 'test value'],
    ],
  ];
}

/*variables array_keys=Array
(
[0] => view
[1] => rows
[2] => title
[3] => options
[4] => context
[5] => icon
[6] => icon_position
[7] => icon_only
[8] => theme_hook_original
[9] => attributes
[10] => title_attributes
[11] => content_attributes
[12] => title_prefix
[13] => title_suffix
[14] => db_is_active
[15] => is_admin
[16] => logged_in
[17] => user
[18] => directory
[19] => default_row_class
[20] => #cache
)*/

/**
 * Implements hook_preprocess_views_view_field().
 *
 *   For replacing current revision field values with latest pending revision field values.
 * This is so we can have themed (orange as example) pending draft rows. To complement the
 * hotpink current draft rows.
 *
 * @todo add {{ status }} to a view row (must be yes / no custom boolean not Yes / No , use lowercase in the view field custom.
 * May 14 2020: Added the implementation for customization on
 * Oct 16 2020: Added content view to be supported.
 */
function agri_admin_preprocess_views_view_field(&$variables) {
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $view = $variables['view'];

  $hasPermission = FALSE;
  if ($variables['logged_in']) {
    $user = \Drupal::currentUser();
    $hasPermission = $user->hasPermission('agrisource pending drafts');
  }
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $otherLang = 'fr';
  if ($lang == 'fr') {
    $otherLang = 'en';
  }

  $view = $variables['view'];
  if ($hasPermission &&
       ($view->id() == 'news' ||
        $view->id() == 'newsatwork_for_home_page' ||
        $view->id() == 'content' ||
  // Added for Moderated Content view related code block below.
        $view->id() == 'moderated_content' ||
        $view->id() == 'moderation_dashboard_content_locked' ||
        $view->id() == 'view_employmentopportunities' ||
        $view->id() == 'view_news_work')) {
    $field = $variables['field'];
    $row = $variables['row'];
    $nid = $row->_entity->id();
    $vid = $row->_entity->getLoadedRevisionId();

    // This IF block only for Moderated Content view.
    // Returning after this block ends since the rest of the code currently does not apply to this view.
    if (($view->id() == 'moderated_content') || ($view->id() == 'moderation_dashboard_content_locked')) {
      if ($field->field == 'moderation_state') {
        $moderationState = $row->_entity->get('moderation_state')->getString();
        if ($moderationState == 'draft') {
          $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
          if ($node->isPublished()) {
            if ($view->id() == 'moderated_content') {
              $variables['output'] = t('pending draft');
            }
            elseif ($view->id() == 'moderation_dashboard_content_locked') {
              $variables['output'] = t('Pending draft');
            }
          }
        }
      }
      return;
    }

    if ($row->_entity->isPublished() && $latestRevision = AgriAdminHelper::getLatestRevisionOnlyIfDraft($nid, $vid)) {
      if ($field->field == 'status') {
        // This is specifically for the row styling (view -> Format -> settings -> row {{ status }}.
        // title
        // body
        // field_fieldname
        // status
        // nid
        // field_title.
        $variables['output'] = strtolower($variables['output']);
        $variables['output'] = Markup::create(str_replace('yes', 'no pending-draft', $variables['output']));
      }
      elseif ($field->field == 'operations') {
        return;
      }
      elseif ($field->field == 'moderation_state_1') {
        // This is specifically for the row styling (view -> Format -> settings -> row {{ moderation_state_1 }}.
        // Do nothing, for styling purposes, because archived should have another color see css/scss.
        return;
      }
      elseif ($view->id() == 'content' && $field->field == 'moderation_state') {
        $variables['output'] = $variables['output'] . ' + ' . t('pending draft');
        return;
      }
      elseif ($view->id() == 'content' && $field->field == 'name') {
        // This field needs special treatment.
        // @todo Lakshman will probably notice this, will have to replace content author with revision author.
        $user = $latestRevision->getRevisionUser();  // removing the linking because the Author column is currently unlinked in admin/content view.
//        $render_array = ['#markup' => "<a href=\"/" . $lang . "/user/" . $user->id() . "\">" . $user->getAccountName() . "</a>"];
        $variables['output'] = $user->getAccountName();  //Utils::render($render_array);
        return;
      }
      elseif ($field->field == 'node_bulk_form') {
        // There is no fieldable field called 'node_bulk_form' this is a vbo field, so skip it.
        return;
      }
      elseif ($field->field == 'nothing') {
        // There is no fieldable field called 'nothing' this is a views field, so skip it.
        return;
      }
      elseif ($field->field == 'machine_name') {
        // There is no fieldable field called 'machine_name', so skip it.
        return;
      }
      elseif ($field->field == 'edit_node') {
        // There is no fieldable field called 'edit_node', so skip it.
        return;
      }
      elseif ($field->field == 'delete_node') {
        // There is no fieldable field called 'delete_node', so skip it.
        return;
      }
      elseif ($field->field == 'nid') {
        // There is no fieldable field called 'nid', so skip it.
        return;
      }
      elseif ($field->field == 'tid') {
        // There is no fieldable field called 'tid', so skip it.
        return;
      }
      else {
        $valueCurrent = '';
        if ($lang == 'fr') {
          $valueCurrent = $row->_entity->getTranslation($lang)->get($field->field)->value;
        }
        else {
          $valueCurrent = $row->_entity->get($field->field)->value;
        }
        // Already in current language.
        $valuePending = $latestRevision->get($field->field)->value;
        // Replace characters in the field output.
	if (!isset($valuePending)) {
          $valuePending = '';
	}       
        if (!isset($valueCurrent)) {
          // PHP 8.1 compatibility, prevent null str_replace.
          $valueCurrent = '';
        }
        $variables['output'] = Markup::create(str_replace($valueCurrent, $valuePending, $variables['output']));
        if ($view->id() != 'content' && ($field->field == 'title' || $field->field == 'field_title')) {
          $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid);
          $urlPathToLatest = '/node/' . $nid . '/latest';
          // Replace path to node in the field output.
          $variables['output'] = Markup::create(str_replace($alias, $urlPathToLatest, $variables['output']));
        }
        elseif ($view->id() == 'content' && ($field->field == 'title' || $field->field == 'field_title')) {
          $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid);
          $urlPathToLatest = "/$lang/node/$nid/latest";
          // Replace path to node in the field output.
          $variables['output'] = Markup::create($variables['output'] . ' <a href="' . $urlPathToLatest . '"><b>( ' . t('Pending Draft') . ' )</b></a>');
        }
      }
    }
  }

  if ($view->id() == 'moderated_content' || $view->id() == 'content') {
    $field = $variables['field'];
    if ($field->field == 'nid' || $field->field == 'id') {
      $row = $variables['row'];
      $nid = $row->_entity->id();
      // Retrieves a \Drupal\Core\Database\Connection which is a PDO instance.
      // NORMALLY DO NOT USE THIS, use \Drupal::database() instead.
      // Only doing this here because of dcr_id for altered table (not a Drupal column).
      $connection = Database::getConnection();
      $dcr_id_column_exists = $connection->schema()->fieldExists('node', 'dcr_id');
      if (!$dcr_id_column_exists) {
        return;
      }
      // Retrieves a PDOStatement object
      // http://php.net/manual/en/pdo.prepare.php
      $sth = $connection->select('node', 'n')
        ->fields('n', ['dcr_id'])
        ->condition('n.nid', $variables['output'], '=');

      // Execute the statement.
      $data = $sth->execute();

      // Get only one result.
      $result = $data->fetch();
      $value = $result->dcr_id;
      if (property_exists($result, 'dcr_id') && isset($result->dcr_id)) {
        $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
        if ($langcode == 'en') {
          $variables['output'] = Markup::create("<span class='nid'>" . $variables['output'] . "</span><span class='legacy-dcr-id'>$value</span>" .
          '<span class="fa fa-clipboard" style="margin-left: 10px" title="Copy dcr_id"></span>');
        }
        else {
          $variables['output'] = Markup::create("<span class='nid'>" . $variables['output'] . "</span><span class='legacy-dcr-id'>$value</span>" .
          '<span class="fa fa-clipboard" style="margin-left: 10px" title="Copier le dcr_id"></span>');
        }
      }
    }
  }

  if ($view->id() == 'view_employmentopportunities') {
    $field = $variables['field'];
    $row = $variables['row'];
    $node = $row->_entity;
    if ($node->hasTranslation($lang)) {
      // Safely get translation.
      // fix French Translation issues.
      $translatednode = $node->getTranslation($lang);
    }
    else {
      // Failsafe default.
      $translatednode = $node;
    }
    $classification = '';
    if ($field->field == 'field_classification' && $node->getType() == 'empl') {
      // If ($row->_entity->get($field->field)->value) {.
      if ($paragraph_field_items = $translatednode->get('field_classification')->getValue()) {
        $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');
        // Collect paragraph field's ids.
        $ids = array_column($paragraph_field_items, 'target_id');
        // Load all paragraph objects.
        $paragraphs_objects = $paragraph_storage->loadMultiple($ids);
        foreach ($paragraphs_objects as $paragraph) {
          // Get field from the paragraph.
          $groupval    = $paragraph->get('field_class_id')->value;
          $subgroupval = $paragraph->get('field_class_sub')->value;
          $levelval    = $paragraph->get('field_class_level')->value;
          $tmpText     = '';
          // Do something with $text...
          if ($subgroupval) {
            $tmpText = $groupval . '-' . $subgroupval . '-' . $levelval;
          }
          else {
            $tmpText = $groupval . '-' . $levelval;
          }
          if (strlen($classification) > 0) {
            $classification = $classification . ', ' . $tmpText;
          }
          else {
            $classification = $tmpText;
          }
        }
        $ptitle = $translatednode->get('title')->value;
        // Friendly url explained: https://drupal.stackexchange.com/a/275438/99288 .
        // Relative url.
        $friendly_url = $translatednode->toUrl()->toString();
        // $friendly_url = $node->toUrl()->setAbsolute()->toString(); // Or absolute url.
        // @Note to James, previously, $nid was undefined, so this was producing an invalid link.
        // So I changed it to the friendly url instead as a fix and improvement.
        $titlefield = '<a href="' . $friendly_url . '"' . ' hreflang="' . $lang . '">' . $ptitle . '</a>';
        $variables['output'] = Markup::create($classification . ' ' . $titlefield);
      }
    }

  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function agri_admin_node_insert(EntityInterface $entity) {
  $entity_id = $entity->id();

  $action = 'insert';
  AgriAdminHelper::addToLog(__function__);
  drupal_register_shutdown_function('_helper_update_process', $action, $entity_id, $entity->bundle());
  drupal_register_shutdown_function('_helper_locking_content', $action, $entity_id, $entity->bundle(), $entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function agri_admin_node_update(EntityInterface $entity) {
  $entity_id = $entity->id();
  $action = 'update';
  // AgriAdminHelper::addToLog(__function__);
  global $import_override;
  if (!isset($import_override) || $import_override == FALSE) {
    drupal_register_shutdown_function('_helper_update_process', $action, $entity_id, $entity->bundle());
    drupal_register_shutdown_function('_helper_locking_content', $action, $entity_id, $entity->bundle(), $entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function agri_admin_node_presave(EntityInterface $entity) {
  // Exit early if possible.
  if ($entity->getEntityTypeId() != 'node') {
    return;
  }
  // Custom code goes here:
  global $import_override;

  $langcode = $entity->language()->getId();
  $menu_link_manager = \Drupal::service('plugin.manager.menu.link');
  $menu_links = $menu_link_manager->loadLinksByRoute('entity.node.canonical', ['node' => $entity->id()]);
  $menu_link = reset($menu_links);
  if ($menu_link) {
    $parent = $menu_link->getParent();
    if ($parent) {
      $parent = $menu_link_manager->createInstance($parent);
      // Get the current menu parent's url in UI.
      $parent_url = $parent->getUrlObject()->toString();
      $langprefix = '/' . $langcode;
      // Only compares parent's url/part and invalidate cache at the first time save
      // when current UI langcode == current UI parent menu link's langcode else the second time save, do nothing.
      if (isset($parent_url) && strpos($parent_url, $langprefix) !== FALSE) {
        $parent_url = str_replace($langprefix, '', $parent_url);
        $path = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $entity->id(), $langcode);
        // Remove the last link of the path to get the parent path.
        $patharray = explode('/', $path);
        array_pop($patharray);
        array_shift($patharray);
        $parent_path = '';
        foreach ($patharray as $str) {
          $parent_path = $parent_path . '/' . $str;
        }
        if ($parent_url != $parent_path) {
          \Drupal::service('cache.render')->invalidateAll();
          \Drupal::service('cache.menu')->invalidateAll();
        }
      }
    }
  }

  $entity_id = $entity->id();
  // Set Authored by to current user if role is creator except during Peer Review.
  $current_author_id = $entity->getOwnerId();
  $current_user = \Drupal::currentUser();
  $current_user_id = $current_user->id();
  $roles = $current_user->getRoles();
  $authored_on = $entity->getCreatedTime();
  $content_type = $entity->bundle();

  if ($content_type == 'page' || $content_type == 'landing_page' || $content_type == 'empl' || $content_type == 'news') {
    $changed_time = $entity->getChangedTime();
    $date_issued = $entity->get('field_issued')->getString();
    $date_modified = $entity->get('field_modified')->getString();
    $moderation_state = $entity->moderation_state->value;
    $created_by = $entity->get('field_created_by')->getString();
    // AgriAdminHelper::addToLog(print_r('Current: '.$current_user, TRUE), TRUE);.
    if (empty($created_by)) {
      if ($entity->isNew()) {
        $entity->set('field_created_by', $current_user->getAccountName());
      }
      else {
        $admin_username = User::load(1)->getAccountName();
        $entity->set('field_created_by', $admin_username);
      }
    }

    $peer_review_status = '';
    if ($content_type == 'page' || $content_type == 'landing_page') {
      $update_date_modified_str = $entity->get('field_update_date_modified')->getString();
      $peer_review_status = $entity->get('field_peer_review')->getString();
      if ($moderation_state == 'published' || $moderation_state == 'archived') {
        $entity->set('field_peer_review', '');
      }
    }
    else {
      // Just making not zero and different from 1 for debug ease.
      $update_date_modified_str = '2';
    }

    $is_ia_role = FALSE;
    foreach ($roles as $role) {
      if ($role == 'ia') {
        $is_ia_role = TRUE;
        continue;
      }
    }
    if ($moderation_state == 'published') {
      $dt = new DateTime();
      if (empty($date_issued)) {
        $entity->set('field_issued', $dt->format('Y-m-d'));
        $entity->set('field_modified', $dt->format('Y-m-d'));
        $date_modified = $dt->format('Y-m-d');
        $date_issued = $date_modified;
      }

      if ($update_date_modified_str == '0' || $is_ia_role == TRUE || (isset($import_override) && $import_override)) {
        if(new DateTime($date_modified) > $dt) {
          $date_modified = $dt->format('Y-m-d');
          $entity->set('field_modified', $date_modified);
        }
        if(new DateTime($date_modified) < new DateTime($date_issued)) {
          $date_modified = $date_issued;
          $entity->set('field_modified', $date_modified);
        }

        // The changed field is translateable, must set value twice, otherwise unexpected issues during import.
        if ($entity->get('changed')->getFieldDefinition()->isTranslatable()) {
          // For some reason we enabled translation for changed field on this.
          if ($langcode == 'en') {
            if ($entity->hasTranslation('fr')) {
              $entity->getTranslation('fr')->set('changed', strtotime($date_modified));
            }
            if ($entity->hasTranslation('en')) {
              $entity->getTranslation('en')->set('changed', strtotime($date_modified));
            }
          }
          else {
            if ($entity->hasTranslation('en')) {
              $entity->getTranslation('en')->set('changed', strtotime($date_modified));
            }
            if ($entity->hasTranslation('fr')) {
              $entity->getTranslation('fr')->set('changed', strtotime($date_modified));
            }
          }
        }
        else {
          // If translation of this field is disabled make sure still works.
          $entity->set('changed', strtotime($date_modified));
        }
      }
      else {
        $entity->set('field_modified', $dt->format('Y-m-d'));
      }
    }

    // AgriAdminHelper::addToLog('update_date_modified_str: ' . $update_date_modified_str, TRUE);.
  }

  foreach ($roles as $value) {
    $role = $value;
    if (($role == 'creator' &&  empty($peer_review_status)) || $role == 'news_ccpub' || $role == 'empl_cspub') {
      // AgriAdminHelper::addToLog('presave called for ' . $entity->language()->getId() . ' ' . $entity->id(), TRUE);.
      $langcode = $entity->language()->getId();
      if ($langcode == 'en') {
        $entity->getTranslation('fr')->setOwnerId($current_user_id);
      }
      else {
        $entity->getTranslation('en')->setOwnerId($current_user_id);
      }
      $entity->setOwnerId($current_user_id);
    }
    $entity->set('created', time());
  }
}

/**
 * Helper function for content locking.
 *
 * @param string $action
 *   Is this operation an update or insert?
 * @param int $entity_id
 *   The id of the node.
 * @param string $bundle
 *   The content type, ex: 'page', 'landing_page'.
 * @param Drupal\node\NodeInterface $entity_obj
 *   The node that we need to lock or unlock.
 */
function _helper_locking_content($action, $entity_id, $bundle, NodeInterface $entity_obj = NULL) {
  global $import_override;
  $content_type = $entity_obj->bundle();
  if (!isset($import_override) || $import_override == FALSE) {
    if ($action == 'insert' || $action == 'update') {
      $current_user = \Drupal::currentUser();
      $current_user_id = $current_user->id();
      if ($action == 'update') {
        // AgriAdminHelper::getLatestRevision($entity_id, $vid);.
        $latest = $entity_obj;
      }
      if ($action == 'insert') {
        $latest = $entity_obj;
      }
      $current_author_id = $latest->getOwnerId();
      if (!isset($current_author_id)) {
        $current_author_id = $current_user_id;
      }

      $lock_service = \Drupal::service('content_lock');
      $is_creator = FALSE;
      $is_master = FALSE;
      $is_reviewer = FALSE;
      $roles = $current_user->getRoles();
      foreach ($roles as $value) {
        $role = $value;
        if ($role == 'news_ccpub' || $role == 'empl_cspub') {
          $is_master = TRUE;
          $state = $latest->get('moderation_state')->getString();
          if ($state == 'draft' || $state == 'review_by_reviewer' || $state == 'author_reviewing') {
            $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
            // Finished processing.
            return;
          }
          else {
            $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
          }
        }
        if ($role == 'creator') {
          $is_creator = TRUE;
          $state = $latest->get('moderation_state')->getString();
          $peer_review_status = '';
          if ($content_type == 'page' || $content_type == 'landing_page') {
            $peer_review_status = $latest->get('field_peer_review')->getString();
          }
          if ($state == 'draft' && empty($peer_review_status)) {
            $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
            // Finished processing.
            return;
          }
          else {
            $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
          }
        }
        if ($role == 'reviewer' && $state == 'with_reviewer') {
          $is_reviewer = TRUE;
          // Persist the lock for the reviewer.
          $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
          // Finished processing.
          return;
        }
      }
      // $original_state = $entity_obj->getOriginal('moderation_state')->getString();
      $state = $latest->get('moderation_state')->getString();
      if ($state == 'review_by_reviewer' && !$is_creator && !is_null($entity_obj)) {
        // @todo for Deepani - Call a function that sends an email to the reviewer role.
        // @todo Check the content type of $latest (entity) and do a case, possibly different group email per content type.
      }
      if ($state == 'author_reviewing' && !$is_creator && !is_null($entity_obj)) {
        // Reviewer is rejecting, sends back to author_reviewing, re-assigns the lock to the $current_author_id.
        $lock_service->locking($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
        // @todo for Deepani - Call a function that sends an email to $current_author_id (get author email address) and send email.
      }
      elseif (!$is_creator) {
        // Is neither reviewer, nor creator, therefore release all locks.
        $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_user_id, $latest->getEntityTypeId());
        $lock_service->release($entity_id, $latest->language()->getId(), 'edit', $current_author_id, $latest->getEntityTypeId());
      }
    }
  }
}

/**
 * Processing to support internal page menu link behavior (disabled links).
 */
function _helper_update_process($action, $entity_id, $bundle) {
  global $import_override;
  if (!isset($import_override) || $import_override == FALSE) {
    AgriAdminHelper::addToLog('_helper_update_process action=' . $action . ' : ' . $entity_id . ' : ' . $bundle);
    $menu_link_ids = [];
    $menu_link_ids = AgriAdminHelper::postCreateOrUpdateAutoTranslate($action, $entity_id, $bundle);
    // AgriAdminHelper::postUpdateProcess($action, $entity_id, $bundle);.
    if ($bundle == 'page') {
      AgriAdminHelper::disableMenuLink(NULL, $entity_id, 'main', TRUE);
      AgriAdminHelper::disableMenuLink(NULL, $entity_id, 'sidebar');
    }

    if (\Drupal::currentUser()->isAuthenticated()) {
      $content_type = $bundle;
      $entity = \Drupal::entityTypeManager()->getStorage('node')->load($entity_id);
      if ($content_type == 'page') {
        if (isset($entity->moderation_state)) {
          $moderation_state = $entity->moderation_state->value;
          if ($moderation_state == 'archived') {
            if (AgriAdminHelper::menuLinkAction($entity_id, 'main', 'delete')) {
              AgriAdminHelper::addMessage(t('Menu link deleted for "%type" now "archived" node id: %id', [
                '%id' => $entity_id,
                '%type' => 'Internal page',
              ]
                )
              );
            }
            else {
              AgriAdminHelper::addMessage(t('Menu link not found for now "archived" %type node id: %id', [
                '%id' => $entity_id,
                '%type' => 'page',
              ]
                )
              );
            }
          }
        }
      }
      if ($content_type == 'landing_page') {
        if (isset($entity->moderation_state)) {
          $moderation_state = $entity->moderation_state->value;
          if ($moderation_state == 'archived') {
            if (AgriAdminHelper::menuLinkAction($entity_id, 'main', 'disable')) {
              AgriAdminHelper::addMessage(t('Menu link disabled for "%type" now "archived" node id: %id', [
                '%id' => $entity_id,
                '%type' => 'Landing page',
              ]
                )
              );
            }
            else {
              AgriAdminHelper::addMessage(t('Menu link not found for now "archived" %type node id: %id', [
                '%id' => $entity_id,
                '%type' => 'Landing page',
              ]
                )
              );
            }
          }
          if ($moderation_state != 'archived' && AgriAdminHelper::menuLinkExists($entity_id, 'main')) {
            $result_code = AgriAdminHelper::menuLinkAction($entity_id, 'main', 'enable');
          }
        }
      }
    }
  }
}


/**
 * Implements hook_form_node_news_form_alter().
 */
function agri_admin_form_node_news_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $route_match = Utils::getRouteName();
  if ($route_match == 'entity.node.canonical') {
    // For empl submit.
    $form['#attached']['library'][] = 'agri_admin/agri-news-submit';
    // For empl submit.
    $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit_css';
    if (\Drupal::currentUser()->isAuthenticated()) {
      // For empl submit.
      $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit-simple';
    }
    $form['actions']['preview']['#weight'] = -99;
    $form['actions']['#weight'] = 10;
    $form['actions']['submit']['#value'] = t('Submit');
  }
  if (\Drupal::currentUser()->isAnonymous()) {
    // Remove/do not render these form elements from anonymous user.
    $form['revision_log']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
    $form['revision']['#access'] = FALSE;
    $form['field_keywords']['#access'] = FALSE;
    $form['field_description']['#access'] = FALSE;
    $form['moderation_state']['#access'] = FALSE;
    // End of remove these form elements from anonymous user:
    $form['actions']['preview']['#weight'] = -99;
    // See js/agri-empl-or-news-submit.js previewInNewTab().
    // For empl submit.
    $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit_css';
    $form['actions']['#weight'] = 10;
    $form['actions']['submit']['#value'] = t('Submit');
    // $form['#attributes']['target'] = '_blank';
    // $form['#attributes']['novalidate'] = 'novalidate';
  }
}

/**
 * Implements hook_form_node_empl_form_alter().
 */
function agri_admin_form_node_empl_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $route_match = Utils::getRouteName();
  if ($route_match == 'entity.node.canonical') {
    $form['actions']['preview']['#weight'] = -99;
    // For empl submit.
    $form['#attached']['library'][] = 'agri_admin/agri-empl-submit';
    // For empl submit.
    $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit_css';
    if (\Drupal::currentUser()->isAuthenticated()) {
      // For empl submit.
      $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit-simple';
    }
    $form['actions']['#weight'] = 5;
    $form['actions']['submit']['#value'] = t('Submit Request');
  }
  if (\Drupal::currentUser()->isAnonymous()) {
    // Remove/do not render these form elements from anonymous user.
    $form['revision_log']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;

    // $debug_this = $form['field_classification'];
    // AgriAdminHelper::addToLog('classif debug: <pre>' . print_r(array_keys($debug_this),TRUE) . '</pre>' , TRUE);
    $form['revision']['#access'] = FALSE;
    $form['field_keywords']['#access'] = FALSE;
    $form['field_description']['#access'] = FALSE;
    $form['moderation_state']['#access'] = FALSE;
    // End of remove these form elements from anonymous user:
    $form['actions']['preview']['#weight'] = -99;
    // See js/agri-empl-or-news-submit.js previewInNewTab().
    // For empl submit.
    $form['#attached']['library'][] = 'agri_admin/agri-empl-news-submit_css';
    $form['actions']['#weight'] = 5;
    $form['actions']['submit']['#value'] = t('Submit Request');
    // $form['#attributes']['target'] = '_blank';
    // $form['#attributes']['novalidate'] = 'novalidate';
  }
}

/**
 * Implements agri_admin_form_submit().
 */
function agri_admin_form_newsorempl_submit(array $form, FormStateInterface $form_state) {
  $current_user = \Drupal::currentUser();
  if ($current_user->isAnonymous()) {
    $entity = $form_state->getFormObject()->getEntity();
    $entity->set('moderation_state', 'draft');
    $front_url = Url::fromRoute('<front>');
    $form_state->setRedirectUrl($front_url);
  }
}

/**
 * Implements hook_form_page_submit().
 */
function agri_admin_form_page_submit(array $form, FormStateInterface $form_state) {
  // Only call for internal page or landing page with archived moderation state.
  $entity = $form_state->getFormObject()->getEntity();
  $moderation_state = $entity->moderation_state->value;
  if ($moderation_state == 'delete') {
    $language = \Drupal::languageManager()->getCurrentLanguage();
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $url = Url::fromRoute('<front>', [], ['language' => $language]);
    $title = $entity->getTitle();
    $msg = t('The archived content <em class="placeholder"> %title</em> has been deleted.', ['%title' => $title]);
    $nid = $entity->id();
    $node = Node::load($nid);
    if (isset($node)) {
      $node->delete();
      // Clearing buff message and reset deletion message.
      \Drupal::messenger()->deleteAll();
      \Drupal::messenger()->addStatus(['#markup' => $msg]);
      $form_state->setRedirectUrl($url);
    }
  }
}

/**
 * Implements hook_form_node_form_alter().
 */
function agri_admin_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();

  $content_type = $entity->bundle();
  if ($content_type == 'page' || $content_type == 'landing_page' || $content_type == 'empl' || $content_type == 'news') {
    $form['field_issued']['widget'][0]['#disabled'] = TRUE;
    $form['field_created_by']['widget'][0]['#disabled'] = TRUE;
    $form['field_dc_date_created']['widget'][0]['#disabled'] = TRUE;
    // For page and landing page edit/add css.
    $form['#attached']['library'][] = 'agri_admin/page';
    // Add validation functionality to prevent the broken links or misused linkit before the page is published.
    if ($content_type == 'page' || $content_type == 'landing_page') {
      $form['#validate'][] = 'agri_admin_publishpage_referredlinks_validation';
    }
    // Attached agri_admin_form_page_submit event handler to page, landing page, empl and news.
    $moderation_state = $entity->moderation_state->value;
    if ($moderation_state == 'archived') {
      $form['actions']['submit']['#submit'][] = 'agri_admin_form_page_submit';
    }
    // Custom action after the data is submitted.
    // $form['actions'][$action]['#submit'][] = 'agri_admin_form_submit'i;.
    $current_user = \Drupal::currentUser();
    if ($current_user->isAnonymous()) {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          $form['actions'][$action]['#submit'][] = 'agri_admin_form_newsorempl_submit';
        }
      }
    }

    // Copying fields to label:
    if (isset($form['field_dc_date_created']['widget'][0])) {
      $date_created_date = $form['field_dc_date_created']['widget'][0]['value']['#default_value'];
      if (is_object($date_created_date)) {
        $form['field_dc_date_created']['widget'][0]['value']['#title'] = t('dc.date.created: @date_created', [
          '@date_created' => $date_created_date->format('Y-m-d'),
        ]
        );
      }
      else {
        $form['field_dc_date_created']['widget'][0]['value']['#title'] = t('dc.date.created: @date_created', [
          '@date_created' => '',
        ]
        );
      }
      $form['field_dc_date_created']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_created_by']['widget'][0])) {
      $created_by = $form['field_created_by']['widget'][0]['value']['#default_value'];
      if (!empty($created_by)) {
        $form['field_created_by']['widget'][0]['value']['#title'] = t('Created by: @created_by', [
          '@created_by' => $created_by,
        ]
        );
      }
      else {
        $form['field_created_by']['widget'][0]['value']['#title'] = t('Created by:');
      }
      $form['field_created_by']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_issued']['widget'][0])) {
      $date_issued = $form['field_issued']['widget'][0]['value']['#default_value'];
      if (is_object($date_issued)) {
        $form['field_issued']['widget'][0]['value']['#title'] = t('dcterms:issued @date_issued', [
          '@date_issued' => $date_issued->format('Y-m-d'),
        ]
        );
      }
      else {
        $form['field_issued']['widget'][0]['value']['#title'] = t('dcterms:issued:');
      }
      $form['field_issued']['#attributes']['class'] = 'hidden-input-box';
    }

    if (isset($form['field_modified']['widget'][0])) {
      $date_modified = $form['field_modified']['widget'][0]['value']['#default_value'];
      if (is_object($date_modified)) {
        $form['field_modified']['widget'][0]['value']['#title'] = t('dcterms:modified: @date_modified', [
          '@date_modified' => $date_modified->format('Y-m-d'),
        ]
        );
      }
      else {
        $form['field_modified']['widget'][0]['value']['#title'] = t('dcterms:modified:');
      }
    }

    if ($content_type == 'page' || $content_type == 'landing_page') {
      $moderation_state = $entity->moderation_state->value;
      $peer_review_status = $entity->get('field_peer_review')->getString();

      if ($entity->isNew()) {
        $form['field_peer_review']['#disabled'] = TRUE;
      }
      elseif ($moderation_state == 'published' || $moderation_state == 'archived') {
        $form['field_peer_review']['#disabled'] = TRUE;
        $form['field_tracking_number']['widget'][0]['value']['#default_value'] = '';
      }
      elseif ($moderation_state == 'draft' &&  empty($peer_review_status)) {
        // Do not enable peer reviewed.
        $form['field_peer_review']['widget']['#options_attributes']['peer_reviewed']['disabled'] = 'disabled';
      }
    } //End handle Peer_Review for page/landing_page only.
  }// End page/landing_page/news/empl.

  // Change expiry date field as a required field for node_news_edit_form.
  if ($form_id == 'node_news_edit_form') {
    if (User::load(\Drupal::currentUser()->id())->hasRole('news_ccpub')) {
      if (isset($form['field_newsexpirydate'])) {
        $form['field_newsexpirydate']['widget'][0]['#required'] = TRUE;
        $form['field_newsexpirydate']['#required'] = TRUE;
        $form['field_newsexpirydate']['#element_validate'][] = 'agri_admin_expirydatevalidator';
      }
    }
  }

  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  foreach ($roles as $role) {
    if ($role == 'ia') {
      foreach ($form as $key => $value) {
        if (isset($value)) {
          if (isset($key) && strpos($key, '_meta') == FALSE) {
            if (isset($key) && strpos($key, 'field_') !== FALSE) {
              $form[$key]['#disabled'] = TRUE;
            }
          }
        }
      }
      $form['title']['#disabled'] = TRUE;
      $form['layout_selection']['#disabled'] = TRUE;
      $form['field_description']['#disabled'] = FALSE;
      $form['field_keywords']['#disabled'] = FALSE;
      $form['field_subject']['#disabled'] = FALSE;
      if ($content_type == 'page' || $content_type == 'landing_page') {
        $peer_review_status = $entity->get('field_peer_review')->getString();
        if (!empty($peer_review_status)) {
          $form['field_description']['#disabled'] = TRUE;
          $form['field_keywords']['#disabled'] = TRUE;
          $form['field_subject']['#disabled'] = TRUE;
          $form['field_meta_type']['#disabled'] = TRUE;
          $form['actions']['#disabled'] = TRUE;
        }
      }
    }
  }

}

/**
 * Implements custom validation for checking three cases when the user publishes the page.
 *
 * Case #1: The link contains token.
 *
 * Case #2: The link refers unpublished node.
 *
 * Case #3: The link uses absolute URL path.
 */
function agri_admin_publishpage_referredlinks_validation(&$form, &$form_state) {
  $langcode = AgriAdminHelper::getLang();
  // Default language - body field
  // Since it is in validation stage, i have to get the body value from $form variable instead of node entity.
  $formbodydefault = $form['body']['widget'][0]['value']['#value'];
  $formbody2 = "";
  if ($langcode == 'en' && isset($form['body']['fr'])) {
    $formbody2 = $form['body']['fr']['widget'][0]['value']['#value'];
  }
  else if (isset($form['body']['en'])) {
    $formbody2 = $form['body']['en']['widget'][0]['value']['#value'];
  }
  $entity = $form_state->getFormObject()->getEntity();
  $nType = $entity->bundle();

  // Get the moderation state value from form values.
  $formvalues = $form_state->getValues();
  $tmp = array_pop($formvalues['moderation_state']);
  $node_mstate = array_pop($tmp);
  if (($nType == 'page' || $nType == 'landing_page') && ($node_mstate == 'published')) {
    $foundtokenhref = FALSE;
    agri_admin_checkurltoken($formbodydefault, $foundtokenhref, $langcode);
    agri_admin_checkurltoken($formbody2, $foundtokenhref, $langcode);

    // Check unpublished node.
    $foundunpublishingnode = FALSE;
    agri_admin_checkpagepublished($formbodydefault, $foundunpublishingnode, $langcode);
    agri_admin_checkpagepublished($formbody2, $foundunpublishingnode, $langcode);

    // Check absolute URL.
    $foundabsoluteurl = FALSE;
    agri_admin_checkabsoluteurl($formbodydefault, $foundabsoluteurl, $langcode);
    agri_admin_checkabsoluteurl($formbody2, $foundabsoluteurl, $langcode);

    // Prevent the user to publish the page.
    if ($foundtokenhref || $foundunpublishingnode || $foundabsoluteurl) {
      $form_state->setRebuild();
    }
  }
}

/**
 * Implements check if the href contains token before the user publishes the current page.
 */
function agri_admin_checkurltoken($formbody, &$foundtokenhref = FALSE, $langcode = 'en') {
  // Token string pattern.
  $tokenmsg = '';
  if ($langcode == 'en') {
    $tokenmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Please remove any links to Preview/Draft pages (pages whose URL contains "auHash").</strong></p>';
  }
  else {
    $tokenmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Veuillez supprimer tous les liens vers les pages d\'aperçu/de projet (pages dont l\'URL contient "auHash").</strong></p>';
  }
  $tokenmsgarray = [];
  Utils::checkUrlToken($formbody, $foundtokenhref, $tokenmsgarray);
  if ($foundtokenhref) {
    $warning = Markup::create($tokenmsg);
    \Drupal::messenger()->addWarning($warning);
  }
  return $foundtokenhref;
}

/**
 * Implements check if the href page is published before the user publishes the current page.
 */
function agri_admin_checkpagepublished($formbody, &$foundunpublishingnode = FALSE, $langcode = 'en') {
  $unpublishingnodemsg = '';
  if ($langcode == 'en') {
    $unpublishingnodemsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Please publish the identified pages first and then publish the current one.</strong></p>';
  }
  else {
    $unpublishingnodemsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Veuillez d\'abord publier les pages identifiées, puis publier la page actuelle.</strong></p>';
  }
  $regex_mediaobj = "/data-entity-type=\"node\" data-entity-uuid=\"([a-z]|[0-9]){8}-(([0-9]|[a-z]){4}-){3}([0-9]|[a-z]){12}\"/";
  $regex_uuid = "/([a-z]|[0-9]){8}-(([0-9]|[a-z]){4}-){3}([0-9]|[a-z]){12}/";
  $publishpagemsgarray = [];
  Utils::checkPagePublished($formbody, $foundunpublishingnode, $publishpagemsgarray);
  if ($foundunpublishingnode) {
    $warning = Markup::create($unpublishingnodemsg);
    \Drupal::messenger()->addWarning($warning);
    foreach ($publishpagemsgarray as $msg) {
      $warning = Markup::create($msg);
      \Drupal::messenger()->addWarning($warning);
    }
  }
  return $foundunpublishingnode;
}

/**
 * Implements check if the href url is absolute URL before the user publishes the current page.
 */
function agri_admin_checkabsoluteurl($formbody, &$foundabsoluteurl = FALSE, $langcode = 'en') {
  $absoluteurlmsg = '';
  if ($langcode == 'en') {
    $absoluteurlmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Please use Linkit to complete the reference.</strong></p>';
  }
  else {
    $absoluteurlmsg = '<p style="color:#e0ac00; font-size:16px;"><strong>Veuillez utiliser Linkit pour compléter la référence.</strong></p>';
  }
  $absoluteurlmsgarray = [];
  Utils::checkAbsoluteUrl($formbody, $foundabsoluteurl, $absoluteurlmsgarray);
  if ($foundabsoluteurl) {
    $warning = Markup::create($absoluteurlmsg);
    \Drupal::messenger()->addWarning($warning);
    foreach ($absoluteurlmsgarray as $msg) {
      $warning = Markup::create($msg);
      \Drupal::messenger()->addWarning($warning);
    }
  }

  return $foundabsoluteurl;
}

/**
 * Implements an expirydate validator.
 *
 * For node_news_edit_form.
 */
function agri_admin_expirydatevalidator($element, &$form_state) {
  if ((empty($element['widget'][0]['value']['#value']['date']))) {
    $form_state->setErrorByName('field_newsexpirydate');
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 *
 * For /node/add/news page.
 */
function agri_admin_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  $previousUrl = \Drupal::request()->server->get('HTTP_REFERER');
  $node_preview = \Drupal::routeMatch()->getParameter('node_preview');
  $node = \Drupal::routeMatch()->getParameter('node');
  $nid = 0;
  $nType = '';
  if ($node_preview) {
    $nType = $node_preview->getType();
  }
  if (isset($node) && !is_string($node) && is_object($node) && method_exists($node, 'getType')) {
    $nType = $node->getType();
    $nid = $node->id();
  }
  if (isset($breadcrumb)) {
    $links = $breadcrumb->getlinks();
    if (is_array($links) && isset($links[0])) {
      $first_breadcrumb_text = $links[0]->getText();
      if ($first_breadcrumb_text == 'Agrisource') {
        // Make sure that the first breadcrumb link starts with 'Home' instead of 'Agrisource'.
        $links[0]->setText(t('Home'));
      }
    }
  }

  // Handle /node/preview page for News.
  if (((isset($result) && strpos($result, '/node/preview/') !== FALSE) && ($nType == 'news'))
    && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // Dynamically handle the route name for News link.
      $news = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'news', '=')
        ->execute();
      if ($news) {
        $langcode = AgriAdminHelper::getLang();
        if (is_array($news)) {
          $first_nid = array_shift($news);
          $news = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
        }
        if ($news->hasTranslation($langcode)) {
          $news = $news->getTranslation($langcode);
        }
        $linkNews = $news->toLink($news->getTitle());
      }
      else {
        $linkNews = Link::createFromRoute(t('News'), 'view.view_news_work.page_1');
      }
      $breadcrumb->addLink($linkNews);
      // The following query is not necessary if the news@work breadcrumb is a view route
      // However if it is a node then it is necessary.
      // During our development cycle news@work was sometimes a node as it was imported this way from legacy.
      // However the actual news@work page is a view page now.
      $news_at_work = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'news@work', '=')
        ->execute();
      if (is_array($news_at_work)) {
        $first_nid = array_shift($news_at_work);
        if ((is_numeric($first_nid) && $first_nid > 0) || strlen((string) $first_nid) == 36) {
          // The above if statement is to avoid an array_flip warning from core.
          // If the news@work breadcrumb item is a view page then we should never need to load this.
          $news_at_work = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
        }
      }
      if ($news_at_work) {
        // This condition is only true if the news@work breadcrumb item is a node,
        // however in the current design it is currently a view page.
        $langcode = AgriAdminHelper::getLang();
        if ($news_at_work->hasTranslation($langcode)) {
          $news_at_work = $news_at_work->getTranslation($langcode);
        }
        $linkNewsatWork = $news_at_work->toLink($news_at_work->getTitle());
      }
      else {
        $linkNewsatWork = Link::createFromRoute(t('News@work'), 'view.view_news_work.page_1');
      }
      $breadcrumb->addLink($linkNewsatWork);
    }
  }

  // Handle /node/preview page for Employment Opportunity form.
  if (((isset($result) && strpos($result, '/node/preview/') !== FALSE) && ($nType == 'empl'))
    && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // Dynamically handle the route name for EO link.
      $hr = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'Human Resources – Services and Information', '=')
        ->execute();
      if ($hr) {
        $langcode = AgriAdminHelper::getLang();
        if (is_array($hr)) {
          $first_nid = array_shift($hr);
          $hr = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
        }
        if ($hr->hasTranslation($langcode)) {
          $hr = $hr->getTranslation($langcode);
        }
        $linkHR = $hr->toLink(t('Human Resources'));
      }
      else {
        $linkHR = Link::createFromRoute(t('Human Resources'), 'view.view_employmentopportunities.page_1');
      }
      $breadcrumb->addLink($linkHR);

      // Manually add the Internal Employment Opportunities view here to match Josep's change.
      $linkview_employmentopportunities = Link::createFromRoute(t('Internal Employment Opportunities'), 'view.view_employmentopportunities.page_1');
      $breadcrumb->addLink($linkview_employmentopportunities);
    }
  }
  elseif ($nid == 50 || Utils::getRouteName() == 'view.view_employmentopportunities.page_1' || (isset($nType) && $nType == 'empl')) {
    if ($breadcrumb) {
      foreach ($links as $key => $link) {
        if ($link->getText() == 'Human Resources – Services and Information') {
          $link->setText('Human Resources');
        }
        elseif ($link->getText() == 'Ressources humaines – Services et renseignements') {
          $link->setText('Ressources humaines');
        }
      }
    }
  }

  if (($result == '/node/add/news') && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // Dynamically handle the route name for News link.
      $news = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'news', '=')
        ->execute();
      if ($news) {
        $langcode = AgriAdminHelper::getLang();
        if (is_array($news)) {
          $first_nid = array_shift($news);
          $news = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
        }
        if ($news->hasTranslation($langcode)) {
          $news = $news->getTranslation($langcode);
        }
        $linkNews = $news->toLink($news->getTitle());
      }
      else {
        $linkNews = Link::createFromRoute(t('News'), 'view.view_news_work.page_1');
      }
      $breadcrumb->addLink($linkNews);
      // Dynamically handle the route name for news at work link
      // The following query is not necessary if the news@work breadcrumb is a view route
      // However if it is a node then it is necessary.
      // During our development cycle news@work was sometimes a node as it was imported this way from legacy.
      // However the actual news@work page is a view page now.
      $news_at_work = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'news@work', '=')
        ->execute();
      if (is_array($news_at_work)) {
        $first_nid = array_shift($news_at_work);
        if ((is_numeric($first_nid) && $first_nid > 0) || strlen((string) $first_nid) == 36) {
          // The above if statement is to avoid an array_flip warning from core.
          // If the news@work breadcrumb item is a view page then we should never need to load this.
          $news_at_work = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
        }
      }
      if ($news_at_work) {
        // This condition is only true if the news@work breadcrumb item is a node,
        // however in the current design it is currently a view page.
        $langcode = AgriAdminHelper::getLang();
        if ($news_at_work->hasTranslation($langcode)) {
          $news_at_work = $news_at_work->getTranslation($langcode);
        }
        $linkNewsatWork = $news_at_work->toLink($news_at_work->getTitle());
      }
      else {
        $linkNewsatWork = Link::createFromRoute(t('News@work'), 'view.view_news_work.page_1');
      }
      $breadcrumb->addLink($linkNewsatWork);
    }
  }

  if (($result == '/node/add/empl') && (\Drupal::currentUser()->isAnonymous())) {
    if ($breadcrumb) {
      $links = $breadcrumb->getlinks();
      $breadcrumb = new Breadcrumb();
      $breadcrumb->addLink($links[0]);
      // Dynamically handle the route name for HR link.
      $hr = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'Human Resources – Services and Information', '=')
        ->execute();
      if ($hr) {
        $langcode = AgriAdminHelper::getLang();
        if (is_array($hr)) {
          $first_nid = array_shift($hr);
          $hr = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
        }
        if ($hr->hasTranslation($langcode)) {
          $hr = $hr->getTranslation($langcode);
        }
        $linkHR = $hr->toLink(t('Human Resources'));
      }
      else {
        $linkHR = Link::createFromRoute(t('Human Resources'), 'view.view_employmentopportunities.page_1');
      }
      $breadcrumb->addLink($linkHR);
      $staffing = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
        ->accessCheck(FALSE)
        ->condition('title', 'Staffing', '=')
        ->execute();
      if (is_array($staffing)) {
        $first_nid = array_shift($staffing);
        $staffing = \Drupal::entityTypeManager()->getStorage('node')->load($first_nid);
      }
      if ($staffing) {
        $langcode = AgriAdminHelper::getLang();
        if ($staffing->hasTranslation($langcode)) {
          $staffing = $staffing->getTranslation($langcode);
        }
        $linkStaffing = $staffing->toLink($staffing->getTitle());
      }
      else {
        $linkStaffing = Link::createFromRoute(t('Staffing'), 'view.view_employmentopportunities.page_1');
      }
      $breadcrumb->addLink($linkStaffing);
    }
  }

  // Logic is for rebuilding the Breadcrumb for the preview latest vesrion and authentication user to edit the page.
  $regpath = '/\/node\/([1-9])\d*\/(latest|moderation-history|layout|delete|edit|revisions)/';
  $regpathlatest = '/\/node\/([1-9])\d*\/(latest|layout)/';
  $latest_bool = FALSE;
  if (preg_match($regpathlatest, $result)) {
    $latest_bool = TRUE;
  }
  if (preg_match($regpath, $result)) {
    $links = $breadcrumb->getlinks();
    $breadcrumb = new Breadcrumb();
    $breadcrumb->addLink($links[0]);
    // www.drupal.org/node/2876622 addCacheContexts for new breadcrumb.
    $breadcrumb->addCacheContexts(['url.path', 'languages']);
    $tmpstr = explode('/', $result);
    if (isset($tmpstr[2]) && is_numeric($tmpstr[2])) {
      $nid = $tmpstr[2];
      $langcode = AgriAdminHelper::getLang();
      $url_alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid, $langcode);
      $aliapthArray = explode('/', $url_alias);
      if ($latest_bool) {
        // Do not add the last menu item.
        array_pop($aliapthArray);
      }
      $tmpPath = '';
      array_shift($aliapthArray);
      foreach ($aliapthArray as $nodetitle) {
        $tmpPath = $tmpPath . '/' . $nodetitle;
        $path = \Drupal::service('path_alias.manager')->getPathByAlias($tmpPath);
        $tmpnidarray = explode('/', $path);
        if (isset($tmpnidarray[2]) && is_numeric($tmpnidarray[2])) {
          $nid = $tmpnidarray[2];
          $link = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
          if ($link) {
            if ($link->hasTranslation($langcode)) {
              $link = $link->getTranslation($langcode);
            }
            // Retrieve Menu title based on langcode
            // i will move the query logic into the util class after the logic is tested on Cloud.
            $system_uri = 'entity:node/' . $nid;
            $result = Utils::getMenuItemTitle($system_uri, $langcode);
            if (isset($result)) {
              $title = $result;
            }
            else {
              // Assign the default node title.
              $title = $link->getTitle();
            }
            $linkNew = $link->toLink($title);
            if (isset($linkNew)) {
              $breadcrumb->addLink($linkNew);
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_preproces_breadcrumb().
 *
 * For /node/add/news page.
 */
function agri_admin_preprocess_breadcrumb(&$variables) {
  if ($variables['breadcrumb']) {
    $request = \Drupal::request();
    $route_match = \Drupal::routeMatch();
    $page_title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
    $current_path = \Drupal::service('path.current')->getPath();
    $result = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

    if (!empty($page_title) && ($result == '/node/add/news') && (\Drupal::currentUser()->isAnonymous())) {
      $variables['breadcrumb'][] = [
        'text' => t('Submit an article for news at work'),
        'attributes' => new Attribute(['class' => ['active']]),
      ];
    }

    if (!empty($page_title) && ($result == '/node/add/empl') && (\Drupal::currentUser()->isAnonymous())) {
      $variables['breadcrumb'][] = [
        'text' => t('Internal Employment Opportunity Request Form'),
        'attributes' => new Attribute(['class' => ['active']]),
      ];
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function agri_admin_preprocess_field_multiple_value_form(&$vars) {
  if (!\Drupal::currentUser()->isAnonymous()) {
    return;
  }
  // Anonymous only logic below.
  // Remove weight option for multivalue fields.
  if (isset($vars['table']['#tabledrag'])) {
    unset($vars['table']['#tabledrag']);
    array_pop($vars['table']['#header']);
    foreach ($vars['table']['#rows'] as &$row) {
      foreach ($row['data'] as $key => $rowrowdata) {
        if (!$rowrowdata['data']) {
          unset($row['data'][$key]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_fieldset_HOOK().
 */
function agri_admin_preprocess_fieldset(&$variables) {
  unset($variables['attributes']['required']);
  unset($variables['attributes']['aria-required']);
  unset($variables['attributes']['aria-invalid']);
}

/**
 * Implements hook_preprocess_select_HOOK().
 */
function agri_admin_preprocess_select(&$variables) {
  if (!isset($variables['element']['#field_name'])) {
    return;
  }
  if (\Drupal::currentUser()->isAnonymous()) {
    if ($variables['element']['#field_name']) {
      if ($variables['element']['#field_name'] == 'field_newstype') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name'] == 'field_to') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name'] == 'field_branch') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name'] == 'field_class_id') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name'] == 'field_class_sub') {
        $variables['attributes']['size'] = 1;
      }

      if ($variables['element']['#field_name'] == 'field_class_level') {
        $variables['attributes']['size'] = 1;
      }
    }
  }
}

/**
 * Implements hook_preprocess_form_element_label_HOOK().
 */
function agri_admin_preprocess_form_element_label(&$variables) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (isset($variables['attributes']['for'])) {
      if ($variables['attributes']['for'] == 'edit-advanced') {
        // This squelches w3c error for label that has no element.
        // Since we have removed edit-advanced section we also adjust its label.
        unset($variables['element']);
        unset($variables['attributes']['for']);
        unset($variables['attributes']['class']);
        $variables['attributes']['class'] = 'sr-only';
      }
    }
  }
}

/**
 * Implements hook_content_moderation_notification_mail_data_alter().
 */
function agri_admin_content_moderation_notification_mail_data_alter(EntityInterface $entity, array &$data) {
  $entitiyLang = $entity->get('langcode')->value;
  // Avoid sending two emails for the same entity (en and fr).
  // The French information will be included in the English email.
  if ($entitiyLang == 'en') {
    $currentModState = $entity->get('moderation_state')->getString();
    $nType = $entity->bundle();
    if ($nType == 'news') {
      // Only send the email when the first draft is created.
      if ($currentModState == 'draft' &&  \Drupal::currentUser()->isAnonymous()) {
        $data['to'][] = $entity->get('field_newssubmitteremail')->value;
        $data['to'][] = $entity->get('field_newsreviewedby')->value;
        // The following emails will be read from the settings.local.php file if specified
        // news_generic_email: aafc.newsatwork-nouvellesalouvrage.aac@canada.ca on prod
        // and aafc.cmswebapps-sgcappsweb.aac@canada.ca on all other environments.
        $data['to'][] = Settings::get('news_generic_email');
        $data['to'][] = Settings::get('comm_advisor_1');
        $data['to'][] = Settings::get('comm_advisor_2');
      }
      elseif ($currentModState == 'published') {
        // When publishing all recepients specified above will recieve an email except the comm_advisor_2.
        $data['to'][] = $entity->get('field_newssubmitteremail')->value;
        $data['to'][] = $entity->get('field_newsreviewedby')->value;
        $data['to'][] = Settings::get('comm_advisor_1');
        $data['to'][] = Settings::get('news_generic_email');
      }
      else {
        $data['to'] = [];
      }
    }
    elseif ($nType == 'empl') {
      // Only send the email when the first draft is created.
      if ($currentModState == 'draft' &&  \Drupal::currentUser()->isAnonymous()) {
        $data['to'][] = $entity->get('field_employmentrequestoremail')->value;
        // The following emails will be read from the settings.local.php file if specified
        // empl_generic_email: aafc.hrcentrerh.aac@canada.ca on prod
        // and aafc.cmswebapps-sgcappsweb.aac@canada.ca on all other environments.
        $data['to'][] = Settings::get('empl_generic_email');
        // Get classification information to display in the email.
        $classification = '';
        if ($paragraph_field_items = $entity->get('field_classification')->getValue()) {
          $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');
          // Collect paragraph field's ids.
          $ids = array_column($paragraph_field_items, 'target_id');
          // Load all paragraph objects.
          $paragraphs_objects = $paragraph_storage->loadMultiple($ids);
          foreach ($paragraphs_objects as $paragraph) {
            // Get field from the paragraph.
            $groupval    = $paragraph->get('field_class_id')->value;
            $subgroupval = $paragraph->get('field_class_sub')->value;
            $levelval    = $paragraph->get('field_class_level')->value;
            $tmpText     = '';
            // Do something with $text...
            if ($subgroupval) {
              $tmpText = $groupval . '-' . $subgroupval . '-' . $levelval;
            }
            else {
              $tmpText = $groupval . '-' . $levelval;
            }
            if (strlen($classification) > 0) {
              $classification = $classification . ', ' . $tmpText;
            }
            else {
              $classification = $tmpText;
            }
          }
        }
        $emplMessage = "<p>Le français suit</p>
        <p>Your request " . "\"" . "<strong>[agri-admin:title]" . ": (" . $classification . ")</strong>" . "\"" . " has been submitted and will be processed for publication on AgriSource by Human Resources within 2 working days.</p>" .
        "<p>To preview this opportunity, visit:&nbsp; [agri-admin:unpublished-url]</p>" .
        "<p>If you have any questions or concerns, please contact your&nbsp;<a data-auth='NotApplicable'
         href='http://intranet.agr.gc.ca/agrisourceprev/AgriDoc.do?id=1548432&amp;lang=eng' rel='noopener noreferrer'
         target='_blank'>Human Resource Advisor, Staffing.</a>
         <hr />
         <p>Votre demande relative à la possibilité d'emploi «&nbsp;<strong>[agri-admin:translation-title]" . ": (" . $classification . ")</strong>&nbsp;» a été présentée et sera traitée aux fins de publication dans AgriSource par les Ressources humaines dans les deux jours ouvrables.</p>
         <p>Pour voir un aperçu de cette possibilité, consultez&nbsp;:&nbsp; [agri-admin:translation-unpublished-url]</p>" .
        "<p>Pour toute question ou préoccupation, veuillez communiquer avec votre&nbsp;<a data-auth='NotApplicable'
          href='http://intranet.agr.gc.ca/agrisourceprev/AgriDoc.do?id=1548428&amp;lang=fra' rel='noopener noreferrer'
          target='_blank'>conseiller(ère) en ressources humaines responsable de la dotation.</a>";

        $data['params']['subject'] = "Your employment opportunity " . "\"" . "[node:title]" . "\"" . " request has been submitted / Votre demande relative à la possibilité d'emploi «&nbsp;[agri-admin:translation-title]&nbsp;» a été présentée.";
        $data['params']['message'] = $emplMessage;
      }
      elseif ($currentModState != 'archived') {
        $data['to'] = [];
      }
    }
    // For basic and landing page CT.
    // Default email list will be used when publishing happens and no emails will be sent when drafts are created.
    else {
      if ($currentModState == 'draft') {
        $data['to'] = [];
      }
    }
  }
  if ($entitiyLang == 'fr') {
    $data['to'] = [];
  }
}

/**
 * Implements hook_token_info().
 */
function agri_admin_token_info() {
  $info = [];
  $info['types']['agri-admin'] = [
    'name' => t('Agri Admin Custom Token'),
    'description' => t('Custom Group to use in content moderation notification emails'),
  ];
  $info['tokens']['agri-admin']['translation-title'] = [
    'name' => t('Translation title'),
    'description' => t('A token to extract the translated node title'),
  ];
  $info['tokens']['agri-admin']['translation-url'] = [
    'name' => t('Translation url'),
    'description' => t('A token to extract the translated URL'),
  ];
  $info['tokens']['agri-admin']['title'] = [
    'name' => 'Title',
    'description' => t('A token to extract the current title for using submission form'),
  ];
  $info['tokens']['agri-admin']['url'] = [
    'name' => t('Url'),
    'description' => t('A token to extract the current URL for when using submission form'),
  ];
  $info['tokens']['agri-admin']['unpublished-url'] = [
    'name' => t('Unpublished url'),
    'description' => t('A token to extract the unpublished URL for anonymous users'),
  ];
  $info['tokens']['agri-admin']['translation-unpublished-url'] = [
    'name' => t('Translation unpublished url'),
    'description' => t('A token to extract the unpublished French URL for anonymous users'),
  ];
  $info['tokens']['agri-admin']['user-agent'] = [
    'name' => t('User agent'),
    'description' => t('A token to display the information of user agent'),
  ];
  $info['tokens']['agri-admin']['public-facing-url'] = [
    'name' => t('Public facing URL'),
    'description' => t('A token to extract the current public facing URL'),
  ];
  $info['tokens']['agri-admin']['translation-public-facing-url'] = [
    'name' => t('Translation Public facing URL'),
    'description' => t('A token to extract the current public facing URL in French'),
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function agri_admin_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'agri-admin' && isset($data['entity']) && $data['entity'] instanceof NodeInterface) {
    $entity = $data['entity'];
    if ($entity->hasTranslation('fr')) {
      $translated_entity = $entity->getTranslation('fr');
    }
    else {
      $translated_entity = $entity;
    }
    $translated_title = $translated_entity->getTitle();
    $translated_url = $translated_entity->toLink()->toString();
    $current_title = $entity->getTitle();
    $current_url = $entity->toLink()->toString();
    $transLangID = $translated_entity->language()->getId();
    $currentLangID = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $nodeID = $entity->id();

    $host = \Drupal::request()->getHost();
    $anonymous_url = str_replace("-admin", "", $host);
    $publicFacing_str = '<a href="https://' . $anonymous_url . '/' . $currentLangID . '/node/' . $nodeID . '">' . $current_title . '</a>';
    $publicFacing_url = Markup::create($publicFacing_str);

    $currentLang = \Drupal::languageManager()->getCurrentLanguage();
    $hashTag = AgriAdminHelper::getHashTag($entity, $currentLang);
    $path = '<a href="' . $hashTag . '">' . $current_title . '</a>';
    $unpublished_url = Markup::create($path);

    $transLang = $translated_entity->language();
    $hashTagTrans = AgriAdminHelper::getHashTag($translated_entity, $transLang);
    $transPath = '<a href="' . $hashTagTrans . '">' . $translated_title . '</a>';
    $translated_unpublished_url = Markup::create($transPath);

    $transPublicFacing_str = '<a href="https://' . $anonymous_url . '/' . $transLangID . '/node/' . $nodeID . '">' . $translated_title . '</a>';
    $translated_publicFacing_url = Markup::create($transPublicFacing_str);
    foreach ($tokens as $name => $original) {
      // Find the desired token by name.
      switch ($name) {
        case 'translation-title':
          $replacements[$original] = $translated_title;
          break;

        case 'translation-url':
          $replacements[$original] = $translated_url;
          break;

        case 'title':
          $replacements[$original] = $current_title;
          break;

        case 'url':
          $replacements[$original] = $current_url;
          break;

        case 'unpublished-url':
          $replacements[$original] = $unpublished_url;
          break;

        case 'translation-unpublished-url':
          $replacements[$original] = $translated_unpublished_url;
          break;

        case 'public-facing-url':
          $replacements[$original] = $publicFacing_url;
          break;

        case 'translation-public-facing-url':
          $replacements[$original] = $translated_publicFacing_url;
          break;
      }
    }
  }
  // Add token for webform only.
  if ($type == 'agri-admin' && !(isset($data['entity']) && $data['entity'] instanceof NodeInterface)) {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'user-agent':
          $useragent = $_SERVER['HTTP_USER_AGENT'];
          $replacements[$original] = $useragent;
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function agri_admin_form_menu_link_content_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id = 'menu_link_content_menu_link_content_form') {
    // AgriAdminHelper::addToLog('form_id ' . $form_id, TRUE);.
    // For hiding disabled items adding checkbox.
    $form['#attached']['library'][] = 'agri_admin/menu-navigation-hide-disabled';
  }

  // @todo convert this logic into a contrib module, BEGIN MENU EDIT/ADD LINK OPTIMISATION HERE:
  $route_match = Utils::getRouteName();
  $current_path = \Drupal::service('path.current')->getPath();
  // Retrieve an array which contains the path pieces.
  $path_args = explode('/', $current_path);
  $menu_link_add_or_edit_optimize = FALSE;
  $menu_name = '';

  if ($route_match == 'entity.menu.add_link_form' && isset($path_args[6])) {
    if ($path_args[4] == 'manage' && $path_args[6] == 'add') {
      $menu_link_add_or_edit_optimize = TRUE;
      $menu_name = $path_args[5] . ':';
    }
  }

  if ($route_match == 'entity.menu_link_content.canonical' && isset($path_args[6])) {
    if ($path_args[4] == 'item' && $path_args[6] == 'edit' && is_numeric($path_args[5])) {
      $mlid = $path_args[5];
      $link = AgriAdminHelper::getMenuLinkFromMlid($mlid);
      $menu_name = $link->getMenuName() . ':';
      // Always disable other menu items, speeds up logic for James logic.
      $menu_link_add_or_edit_optimize = TRUE;
      // $current_user = \Drupal::currentUser();
      // $current_user_id = $current_user->id();
      // $roles = $current_user->getRoles();
      // if (!in_array('administrator', $roles)) {
      //   // Only non-Administrators should see the optimized menu for menu link EDIT.
      //   // We want administrators to be able to move this link around if they wish.
      //   $menu_link_add_or_edit_optimize = TRUE;
      // }
    }
  }
  if ($menu_link_add_or_edit_optimize) {
    foreach ($form['menu_parent']['#options'] as $key => &$value) {
      if (isset($key) && strpos($key, $menu_name) === FALSE) {
        unset($form['menu_parent']['#options'][$key]);
      }
      else {
        // Check interface lang code, if english, look for 'disabled' value.
        // Then if NOT disabled, call logic or function.
        // Check interface lang code, if french, look for 'désactivé' value.
        // Then if NOT désactivé, call logic or function.
        $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
        if ($langcode == 'en' && isset($value) && strpos($value, 'disabled') == FALSE) {
          $keyarray = explode(":", $key);
          if (count($keyarray) > 2) {
            if (AgriAdminHelper::isLinkFrenchOnly($keyarray[2])) {
              unset($form['menu_parent']['#options'][$key]);
            }
          }
        }
        else {
          if ($langcode == 'fr' && isset($value) && strpos($value, 'désactivé') == FALSE) {
            $keyarray = explode(":", $key);
            if (count($keyarray) > 2) {
              if (AgriAdminHelper::isLinkEnglishOnly($keyarray[2])) {
                unset($form['menu_parent']['#options'][$key]);
              }
            }
          }
        }
      }
    }
  }
  // @todo END OF MENU EDIT/ADD LINK OPTIMISATION.
  foreach ($form['menu_parent']['#options'] as $key => &$value) {
    if (isset($value) && strpos($value, '-- ') == 0) {
      // $value =  substr($value,0, 3) . 'level 1. ' . substr( $value,3, strlen($value)) ;
      $form['menu_parent']['#options_attributes'][$key]['class'] = ['class' => 'menu_tree-leve-1'];
    }
    else {
      if (isset($value) && strpos($value, '---- ') == 0) {
        // $value =  substr($value,0, 5) . 'level 2. ' . substr( $value,5, strlen($value)) ;
        $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-2 glyphicon';
      }
      else {
        if (isset($value) && strpos($value, '------ ') == 0) {
          // $value =  substr($value,0, 7) . 'level 3. ' . substr( $value,7, strlen($value)) ;
          $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-3';
        }
        else {
          if (isset($value) && strpos($value, '-------- ') == 0) {
            // $value =  substr($value,0, 9) . 'level 4. ' . substr( $value,9, strlen($value)) ;
            $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-4';
          }
          else {
            if (isset($value) && strpos($value, '---------- ') == 0) {
              // $value =  substr($value,0, 11) . 'level 5. ' . substr( $value,11, strlen($value)) ;
              $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-5';
            }
            else {
              if (isset($value) && strpos($value, '------------ ') == 0) {
                // $value =  substr($value,0, 13) . 'level 6. ' . substr( $value,11, strlen($value)) ;
                $form['menu_parent']['#options_attributes'][$key]['class'] = 'menu_tree-leve-6';
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements agri_admin_views_pre_render() hook.
 */
function agri_admin_views_pre_render(ViewExecutable $view) {
  if ($view->id() != 'content' && $view->id() != 'moderated_content') {
    return;
  }

  $user_roles = \Drupal::currentUser()->getRoles();
  if (in_array('empl_cspub', $user_roles)) {
    $filters = $view->getDisplay()->getOption('filters');
    $filters['type']['value'] = 'empl';
    $view->display_handler->overrideOption('filters', $filters);
  }

  if (in_array('news_ccpub', $user_roles)) {
    $filters = $view->getDisplay()->getOption('filters');
    $filters['type']['value'] = 'news';
    $view->display_handler->overrideOption('filters', $filters);
  }
}

/**
 * Implements agri_admin_form_views_exposed_form_alter hook.
 */
function agri_admin_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $view = $form_state->getStorage('view');
  if ($view['view']->id() != 'content' && $view['view']->id() != 'moderated_content') {
    return;
  }

  $route_match = Utils::getRouteName();
  if ($route_match == 'content_moderation.admin_moderated_content') {
    if ($view['view']->id() == 'moderated_content') {
      $form['#attached']['library'][] = 'agri_admin/agri_moderated_content';
    }
  }

  if (isset($form['type']['#options'])) {
    // Ensure that "- Any -" is 'first', and the other type options are in alphanum order.
    ksort($form['type']['#options']);
  }

  $user_roles = \Drupal::currentUser()->getRoles();
  if (in_array('empl_cspub', $user_roles) && ($form_id == 'views_exposed_form')) {
    // Solve Drupal 9 being more strict about allowed filter values, must also set input in Drupal 9.
    $input = $form_state->getUserInput();
    foreach ($form['type']['#options'] as $key => &$value) {
      $key_label = $form['type']['#options'][$key];
      if (($key != 'empl') && (stripos($key_label, 'empl') === FALSE)) {  // additional condition to handle grouped filters
        unset($form['type']['#options'][$key]);
      }
      else {
        $form['type']['#default_value'] = $value;
        $input['type'] = $key;
        $form_state->setUserInput($input);
      }
    }
  }

  if (in_array('news_ccpub', $user_roles) && ($form_id == 'views_exposed_form')) {
    // Solve Drupal 9 being more strict about allowed filter values, must also set input in Drupal 9.
    $input = $form_state->getUserInput();
    foreach ($form['type']['#options'] as $key => &$value) {
      $key_label = $form['type']['#options'][$key];
      if (($key != 'news') && (stripos($key_label, 'news') === FALSE) && (stripos($key_label, 'nouv') === FALSE)) {  // additional condition to handle grouped filters
        unset($form['type']['#options'][$key]);
      }
      else {
        $form['type']['#default_value'] = $key;
        $input['type'] = $key;
        $form_state->setUserInput($input);
      }
    }
  }

  if (($form_id == 'views_exposed_form') && ($view['view']->id() == 'moderated_content')){
    $input = $form_state->getUserInput();
    if (isset($input['moderation_state'])) {
      $key = $input['moderation_state'];
      // To fix issues introduced in Drupal 10.
      if (!is_string($key)) {
        $input['moderation_state'] = 'All';
        $form_state->setUserInput($input);        
      } else {
        $key_label = $form['moderation_state']['#options'][$key];
        // Including additional condition to handle grouped filters.
        if (($key !== 'draft') && (stripos($key_label, 'draft') === FALSE) && (stripos($key_label, 'brouillon') === FALSE)) {
          $input['status'] = 'All';
          $form_state->setUserInput($input);
        }
      }
    }
  }
}

/**
 * Implements hook_file_validate().
 */
function agri_admin_file_validate(FileInterface $file) {
  if (!(\Drupal::config('filehash.settings')->get('dedupe'))) {
    agri_admin_validate_dedupe_warning($file);
  }
}

/**
 * Checks that file is not a duplicate.
 */
function agri_admin_validate_dedupe_warning(FileInterface $file) {
  $warnings = [];
  $warning = '';
  $langId = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if (!$file->id()) {
    $tablename = AgriAdminHelper::getHashTableName();
    foreach (agri_admin_algos() as $algo) {
      $query = \Drupal::database()->select('{' . $tablename . '}');
      $query->addField('{' . $tablename . '}', 'fid');
      $query->condition($algo, $file->filehash[$algo]);
      $query->range(0, 1);

      if ($fid = $query->execute()->fetchField()) {
        if (\Drupal::currentUser()->hasPermission('access files overview')) {
          try {
            $url = Url::fromRoute('view.files.page_2', ['arg_0' => $fid], ['attributes' => ['target' => '_blank']]);
            $filename = Link::fromTextAndUrl(File::load($fid)->label(), $url)->toString();
            if ($langId == 'en') {
              $warning = Markup::create('This file has already been uploaded as ' . $filename . '.');
            }
            else {
              $warning = Markup::create('Ce fichier a déjà été téléchargé en tant que ' . $filename . '.');
            }
          }
          catch (Exception $e) {
            // Maybe the view was disabled?
            \Drupal::messenger()->addWarning($e->getMessage(), TRUE);
          }
        }
        else {
          if ($langId == 'en') {
            $warning = 'This file has already been uploaded.';
          }
          else {
            $warning = 'Ce fichier a déjà été téléchargé.';
          }
        }
        array_push($warnings, $warning);
        break;
      }
    }
  }
  // Ouput all warning messages.
  foreach ($warnings as $msg) {
    \Drupal::messenger()->addWarning($msg, TRUE);
  }
  return [];
}

/**
 * Returns array of enabled hash algorithms.
 */
function agri_admin_algos() {
  return array_diff(\Drupal::config('filehash.settings')->get('algos'), [0]);
}

/**
 * Implements hook_form_alter().
 */
function agri_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  if (isset($form_id) && strpos($form_id, 'media') !== FALSE && strpos($form_id, 'delete') !== FALSE) {
    $path = \Drupal::request()->getpathInfo();
    $arg = explode('/', $path);
    $index_arg = 0;
    $idx = 0;
    foreach ($arg as $segment) {
      if (is_numeric($segment) && !is_bool($segment)) {
        $index_arg = $idx;
      }
      $idx++;
    }
    if (isset($arg[$index_arg]) && is_numeric($arg[$index_arg])) {
      $mid = $arg[$index_arg];
    }
    else {
      // This should never happen.
      return;
    }
    $media = Media::load($mid);
    $media_name = $media->getName();

    $show_button = TRUE;
    if (isset($media_name) && strpos($media_name, 'Home Slideshow Thumbnav') !== FALSE) {
      $show_button = FALSE;
    }
    if (!$show_button) {
      \Drupal::messenger()->addMessage(
        t('"%title" cannot be deleted because it is required for proper SlideShow functionality!', [
          '%title' => $media_name,
        ]
        ), 'error', TRUE);
      $form['actions']['submit']['#attributes'] = [
        'disabled' => $show_button ? 'enabled' : 'disabled',
      ];
    }
  }

}

/**
 * Implements hook_entity_type_predelete().
 */
function agri_admin_media_predelete(EntityInterface $entity) {
  $media_name = $entity->getName();
  if (isset($media_name) && strpos($media_name, 'Home Slideshow Thumbnav') !== FALSE) {
    $entity_type = $entity->getEntityTypeId();
    $id = $entity->id();
    // This message does not seem to work inside this function.
    \Drupal::messenger()->addMessage(t('"%title" cannot be deleted because it is required for proper SlideShow functionality!', [
      '%title' => $media_name,
    ]), 'error', TRUE);

    $response = new RedirectResponse(Url::fromUri('internal:/' . $entity_type . '/' . $id . '/edit')->toString());
    $response->send();
    exit;
  }
}
