services:
  solr9:
    image: solr:9.9
    ports:
      - "8983:8983"
    ulimits:
      nofile:
        soft: 65000
        hard: 65000
    container_name: agrisource_solr
    volumes:
      # Configset mapping (schema files)
      - ./cloud-config-set:/opt/solr/server/solr/configsets/agrisource/conf
      # Persistent data directory
      - ./solr-data:/var/solr
      # Script
      - ./init-cores.sh:/docker-init/init-cores.sh
    networks:
      default:
        ipv4_address: 172.19.0.9
    environment:
      SOLR_MODULES: "extraction,langid,ltr,analysis-extras"
      CORES: "agrisource core2 core3"
      CONF_PATH: "/opt/solr/server/solr/configsets/agrisource/conf"
    command: [ "bash", "/docker-init/init-cores.sh" ]
    restart: unless-stopped
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
