<?php


use Drupal\agri_admin\AgriAdminHelper;
use Drupal\agri_admin\Utils;

/**
 * @file
 * Primary module hooks for News-Empl module.
 *
 */

/**
 * Implements hook_preprocess_html().
 */
function news_empl_page_attachments(array &$page) {
  // add page meta
  $route_match = Utils::getRouteName();
  if ($route_match == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $anonymous = \Drupal::currentUser()->isAnonymous();
    if ($node->bundle() == 'empl') {
      $page['#attached']['library'][] = 'news_empl/empl-node-css'; // Not yet needed.
    }
    else if ($node->bundle() == 'news') {
      $page['#attached']['library'][] = 'news_empl/news-node-css'; // Not yet needed.
    }
    if ($anonymous && \Drupal::service('path.matcher')->isFrontPage()) {
      // This actually only affects the front page.
      $page['#attached']['library'][] = 'news_empl/anonymous-empl-node-css';
      $page['#attached']['library'][] = 'news_empl/anonymous-news-node-css';
    }
  }
}


/**
 * Implements hook_form_node_news_form_alter().
 */
function news_empl_form_node_news_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $route_match = Utils::getRouteName();
  if ($route_match == 'entity.node.canonical') {
    $form['#attached']['library'][] = 'news_empl/news-form'; // Enhance form css.
  }
}


/**
 * Implements hook_form_node_empl_form_alter().
 */
function news_empl_form_node_empl_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $route_match = Utils::getRouteName();
  if ($route_match == 'entity.node.canonical') {
    $form['#attached']['library'][] = 'news_empl/empl-form'; // Enhance form css.
  }
}
